# 야간 작업 2026-09-09

아침에 이 파일 하나만 보면 되게 쓴다. 단계별로 **무엇을 했나 · 수치 · 커밋 ·
판단이 필요한 것**. 스위치 현황표는 맨 끝.

시작 시점 HEAD: `7ede55a` (실주행 2차 [3] 종료 구간 콘)

---

## [1] 콘 여유 확대 — `gen_placement.cone_margin_m` 0.3 → 1.0 ✅

시나리오 21건을 `--from-yaml` 로 재생성했다 (저장된 정의로 다시 굽는 방식이라
**경로 CSV 는 전부 md5 불변** — 콘 위치만 움직였다). 실패 0건.

회랑 여유 전수 (`finish_cone.finish_gate` 의 `clear_min` [m], 오름차순):

| 시나리오 | 0.3 | **1.0** | Δ |
|---|---:|---:|---:|
| 실경로_01_PathShape03 | +0.10 | **+0.80** | +0.70 |
| 실전주행_교통류_15_우회전25 | +0.27 | +0.97 | +0.70 |
| 실전주행_교통류_18_연속교차로14 | +0.27 | +0.97 | +0.70 |
| 실전주행_교통류_10_좌회전14 | +0.35 | +1.05 | +0.70 |
| 실전주행_교통류_17_직진6 | +0.37 | +1.07 | +0.70 |
| 실전주행_교통류_08_우회전16 | +0.38 | +1.08 | +0.70 |
| 실전주행_교통류_01_좌회전24 | +0.40 | +1.10 | +0.70 |
| 실전주행_교통류_05_직진24 | +0.42 | +1.12 | +0.70 |
| 실전주행_교통류_14_좌회전7 | +0.45 | +1.15 | +0.70 |
| 실전주행_교통류_04_직진2 | +0.50 | +1.20 | +0.70 |
| 실전주행_교통류_06_좌회전 | +0.51 | +1.21 | +0.70 |
| 실경로_02_venue0903 | +0.55 | +1.25 | +0.70 |
| 실전주행_교통류_16_직진20 | +1.95 | +2.64 | +0.70 |
| 실전주행_교통류_09_우회전13 | +2.97 | +3.67 | +0.70 |
| 실전주행_교통류_02_직진11 | +3.18 | +3.88 | +0.70 |
| 실전주행_교통류_12_연속교차로3 | +3.25 | +3.95 | +0.70 |
| 실전주행_교통류_11_직진10 | +3.31 | +4.01 | +0.70 |
| 실전주행_교통류_19_연속교차로11 | +3.70 | +4.40 | +0.70 |
| 실전주행_교통류_03_우회전11 | +4.20 | +4.90 | +0.70 |
| 실전주행_교통류_13_우회전11 | +4.20 | +4.90 | +0.70 |
| 실전주행_교통류_07_연속교차로8 | +6.39 | +7.09 | +0.70 |

| | 0.3 | 1.0 |
|---|---:|---:|
| 최소 | +0.10 | **+0.80** |
| 중앙 | +0.51 | +1.21 |
| 0.6 m 미만 | **12건** | **0건** |
| 음수 | 0 | 0 |

전 건이 정확히 +0.70 (= 1.0 − 0.3) 이동했다 — 콘이 도로 끝 기준이라 여유가
margin 에 선형이다. 이제 **가장 좁은 경로(실경로_01, 폭 2.4 m 연결로)에서도
+0.80 m** 라, "종료선을 못 지난 것이 콘 때문인가" 가 로그에서 바로 갈린다.

pytest (콘 관련 4파일) 68 passed.

주의: `scenarios/` 는 `.gitignore` 대상이라 재생성물은 커밋되지 않는다.
커밋되는 것은 `config/params.yaml` 한 줄 + 근거 주석이다. 다른 사람이 같은
표를 보려면 재생성이 필요하다.

---

## [5] 정적 장애물 회피 — 작업 1 (분석)

배치가 도는 동안 **읽기만** 했다 (규칙 (a)(b) 준수: 제어기 파일 무수정,
replay·pytest 미실행).

### (a) 객체 → 차로 매칭

- 객체에 **차로 정보가 없다.** `run_agent._log_objects` 가 `lane=None` 으로
  박아 넣고([run_agent.py:372](../run_agent.py#L372)), `VtdActor` 에도 차로
  필드가 없다. 콘 로그의 `lane: null` 은 버그가 아니라 설계다.
- 재료는 다 있다: `lg.project(key, x, y)` → `(s, t, dist, idx)`
  ([lanegraph.py:443](../vtd_adapter/lanegraph.py#L443)) 와
  `lg.locate(x, y, yaw, prefer=...)` → 최적 차로 1개
  ([:491](../vtd_adapter/lanegraph.py#L491)). `locate` 는 **1개만** 주므로
  걸친 차로를 못 잡는다 → 세 점(중심 · 좌우 폭 끝) 각각 `locate` 해서
  **합집합**을 취하는 방식이 맞다.
- **둘 곳**: `VtdWorld.update` 가 객체 수신의 단일 관문이다
  ([world.py:73](../vtd_adapter/world.py#L73)) — 여기가 자연스럽지만
  **`VtdWorld` 는 `lg` 를 안 갖고 있다**(`__init__(cfg)` 뿐). `run_agent` 는
  `self.lg` 와 `self.world` 를 둘 다 쥐고 있으므로
  ([run_agent.py:199·207](../run_agent.py#L199)) 생성 시 주입하면 된다.
  → **결정: `VtdWorld(cfg, lg=None)` 로 선택 주입**, `lg` 가 없으면 매칭을
  건너뛴다(목 테스트가 lg 없이 world 를 만든다 — 깨면 안 된다).
- 교차로 안: 연결로는 `neighbor` 가 없어 차로 지도의 hop 이 성립하지 않는다.
  `junction != -1` 이면 매칭은 하되 **passable=False** 로 둔다(시프트 금지는
  이미 `_try_overtake_inner` 의 `reject='junction'` 이 한다).
- 소멸 차로: 폭 < 2 m 는 `passable=False`. 폭은 `lg.lanes[k]['width']` 배열이라
  **해당 s 지점 값**을 봐야 한다(평균 아님 — 테이퍼는 끝에서 0 이 된다).

### (b) 큐 제외

`_is_queue_v2` 는 **bool 하나만** 돌려준다
([kr_rules.py:1369](../team_code/kr_rules.py#L1369)) — 객체 단위 판정을 꺼낼
수 없다. 다만 부산물이 두 개 있다:

- `self._tick_corridor` — 그 틱 회랑 blockers 목록 (틱당 1회 캐시)
- `self._tick_queue` / `self.q_info` — 큐인가 + 근거

즉 **"큐다"가 참이면 그 틱 회랑 객체 전부가 큐**라는 취급이 현재 규약이다.
차로 지도에서 빼려면 같은 규약을 그대로 쓰는 게 안전하다:
`_tick_queue` 가 참인 동안 **`_tick_corridor` 에 든 id 를 차로 지도에서 제외**.
객체별 재판정을 새로 만들면 억제 기준이 두 벌이 된다(CLAUDE.md 위반).
한계: 큐가 **내 차로**에만 성립할 때 옆 차로 정지차까지 빠질 수 있다 —
`_tick_corridor` 가 자차 회랑 기준이라 애초에 옆 차로 객체가 안 들어온다.
따라서 실제로는 안전한 쪽으로만 틀린다.

### (c) `_try_overtake` 현재 흐름 — 갈아끼울 경계

| 단계 | 위치 | 차로 지도가 대체? |
|---|---|---|
| 원복 / SHIFT_HOLD / 활성 중 건너뛰기 | [:2262~2312](../team_code/kr_rules.py#L2262) | 아니오 (그대로) |
| 억제(적색·`_signal_zone`·큐) | [:2316~2352](../team_code/kr_rules.py#L2316) | 아니오 (그대로) |
| 회랑 수집 `_corridor_blockers` | [:2338](../team_code/kr_rules.py#L2338) | **보조** — 트리거는 차로 지도로 |
| WAIT/PREEMPT 시간예산 → `actor` 선정 | [:2363~2394](../team_code/kr_rules.py#L2363) | **예 — 여기가 교체 지점** |
| REACTIVE(`ot_blocked_ticks`) | [:2404](../team_code/kr_rules.py#L2404) | 아니오 (폴백으로 유지) |
| `_chain` 연쇄 병합 | [:2618](../team_code/kr_rules.py#L2618) | 부분 (아래 (h)) |
| **side 루프 2바퀴 + 게이트 7개** | `_side_pass` [:2785](../team_code/kr_rules.py#L2785) | **아니오 — 그대로 쓴다** |
| `_pick_side` | [:3077](../team_code/kr_rules.py#L3077) | **예 — 후보 선택 교체** |
| `gap_fit` → `shift_route_around_actors` | [:3000~3040](../team_code/kr_rules.py#L3000) | 아니오 (그대로) |

**경계는 둘**: ① `actor`·`preempt` 를 정하는 시간예산 블록,
② `for side in ('left','right')` 순회 + `_pick_side`.
게이트 7개(`center_line`·`geom`·`span_into_zone`·`solid`·`occupied`·`kappa`/
`lc_overlap`·`entry_block`)는 **선택된 목표 차로에 그대로 적용**하면 된다 —
현재 `target = lg.neighbor(ego_lane, side)` 한 줄만 "차로 지도가 고른 차로"로
바꾸면 나머지 본문이 그대로 산다.

### (d) 두 칸 램프 — **이미 된다**

`shift_route_smoothly` 가 `_shift_target_wp(idx, side, n_steps)` 를 쓰고, 그
함수는 **이웃을 n_steps 만큼 따라간다**
([route.py:663](../vtd_adapter/route.py#L663)). 지금은 `n_steps` 가
`_shift_target_steps` 에서 "현재 밀린 칸수 k + 1" 로만 나온다(항상 한 칸씩).
→ **필요한 것은 "목표 hop 수"를 넘기는 인자 하나뿐**이다. 좌표 계산·전이·
`lat_shift`(지시등 입력) 갱신은 전부 그 경로를 그대로 탄다.

- 회랑 폭·점선 2개 연속: `_dashed_ahead_m(lg, ego_lane, side, ...)` 는 **한
  칸** 기준이라 2 hop 이면 중간 차로에서 한 번 더 재야 한다 (게이트 보강 필요).
- 램프 길이: `trans_m = max(ot_trans_m, shift_k_s·v)` 는 칸수와 무관하다 →
  **칸수 배로 늘려야** 횡가속이 같다 (커밋 B 에서 `칸수 × 차로폭 / a_lat`).
- 지시등: `lat_shift` 가 변위 크기로 들어가므로 2 칸이면 값만 커지고 부호는
  같다 → **한 번 켜고 유지**가 자연히 성립한다.

### (e) 복귀 없음일 때 지시등·속도캡

**`_lat_adopt` 는 존재하지 않는다** (지시안의 이름은 가정이었던 것으로 보인다).
현재 "기준 배열"은 `planner.original_route_points` + `planner._lat_build` 이고,
`lat_shift[idx] = _lat_build[idx] ± d` 로 매 틱 갱신된다
([route.py:716](../vtd_adapter/route.py#L716)). 즉 **오프셋을 0 으로 되돌리면
지시등이 역방향으로 켜진다** — 지시안이 지적한 `route.py:434` 전례와 같은 축이다.

→ 복귀 없음을 하려면 **`original_route_points`·`_lat_build` 를 새 차로 기준으로
갈아끼우는 함수가 새로 필요하다** (커밋 C 의 핵심). 손댈 곳 3 : `lat_shift`
기준(`_lat_build`), `_shift_target_steps` 의 k 계산 기준, `planned_lateral_offsets`.

### (f) 다음 교차로 유효 차로 + 데드라인 — **재사용 가능**

`_ns_turn_lane_pending` ([:1806](../team_code/kr_rules.py#L1806)) 이 이미
`route['valid_entry_lanes']` 로 "지금 차로가 다음 짝 진입에 유효한가" 와
데드라인 `s1 − route_s ≤ max(ot_trans_m, shift_k_s·v) + ns_turn_margin_m` 을
계산한다. **그대로 부르면 된다** — 반환 dict 에 `want`(유효 차로 목록)·
`left_m`·`need_m` 이 다 있다.

### (g) 감속 후보 자리

`apply` 의 min() 사다리 [:4540 부근](../team_code/kr_rules.py#L4540) —
`_lc_speed_cap` 바로 옆에 넣는다. **[2] 확정 사실대로 상한형**이므로
`cap_cand` 에도 같이 넣어야 `cap_binds` 가 서고 P + `a_cap_dec_max` 축을 탄다.
`lc_speed_cap` 과 통합은 **하지 않는다** — 창 재료가 다르다(LC 는
`planner.lc_ramps`, 회피는 차로 지도). 같은 자리의 별도 후보로 둔다.

### (h) `_chain`·`span_extend` vs `free_run`

- `_chain` 은 **회랑 안 연쇄 병합**이라 `free_run`(차로별 첫 장애물까지 거리)이
  대신하지 못한다. `free_run` 은 "어디까지 비었나", `_chain` 은 "span 을 어디까지
  늘려야 하나" 로 쓰임이 다르다 → **둘 다 유지**.
- `span_extend` 는 활성 span 의 **끝만** 늘리는 사후 보정이다. 차로 지도가
  목표를 처음부터 제대로 고르면 발동이 줄겠지만, 예측 못 한 객체에 대한
  안전망이므로 **유지**.

### 결정 요약 (커밋 A~C 설계)

1. `VtdWorld(cfg, lg=None)` 주입 + 객체 3점 투영 → `actor.lanes`(집합).
2. 차로 지도는 **kr_rules** 에 둔다 (`planner.lg` · `_tick_corridor` ·
   `_tick_queue` 를 다 쓰므로). `VtdWorld` 는 매칭까지만.
3. 게이트 7개·`gap_fit`·`shift_route_around_actors` 는 **손대지 않는다**.
   `target` 한 줄과 `actor` 선정만 교체.
4. 두 칸은 `_shift_target_wp` 의 `n_steps` 인자화로 가능 — 단 `_dashed_ahead_m`
   를 hop 별로 반복 검사해야 한다.
5. **복귀 없음(커밋 C)이 가장 무겁다** — 기준 배열 교체 함수가 새로 필요하고
   지시등·속도캡·`_shift_target_steps` 3곳이 그 기준을 공유한다.

---

## [3] quick 나머지 배치 — **부분 성공 (5건 막힘)**

`logs/batch/20260909_000141` (6건) + `20260909_001824` (재시도 5건).

| 시나리오 | 상태 | 거리 | 감점 | 주요 위반 |
|---|---|---:|---:|---|
| 실경로_01_PathShape03 | **완주** | 870.1 m | −15 | 차로유지2 −6, 장애물1 −6, 지시등1 −3 |
| 실경로_02_venue0903 *(앞서 실행)* | **완주** | 752.0 m | −15 | 충돌1 −6, 차로유지1 −3, 정지선1 −3, 지시등1 −3 |
| 실전주행_교통류_07_연속교차로8 | ❌ VTD 9910 무응답 | — | — | — |
| 실전주행_교통류_09_우회전13 | ❌ VTD 9910 무응답 | — | — | — |
| 실전주행_교통류_10_좌회전14 | ❌ VTD 9910 무응답 | — | — | — |
| 실전주행_교통류_11_직진10 | ❌ VTD 9910 무응답 | — | — | — |
| 실전주행_교통류_18_연속교차로14 | ❌ VTD 9910 무응답 | — | — | — |

**실경로_01 은 이전(20260908_222954)에 blocked(미완주, −12)였다 → 이번에 완주.**
두 실경로 모두 완주다.

### 막힌 것 — 실전주행_교통류_* 5건

`→ VTD 9910 무응답 (120s 예열 대기 초과)`. **2회 시도 모두 같은 지점에서 동일**
(전이 아님). 확인한 것:

- VTD PC 48179·9910 **둘 다 접속됨** (실패 직후 확인).
- XML 은 VTD PC 에 **있다** — `ls` 로 확인, 3건 표본 401 KB/403 KB/397 KB.
- 실경로_01·02 는 **같은 세션에서 정상 로드·주행**했다. 즉 연결·경로·권한 문제가
  아니고 **이 5개 시나리오 한정**이다.
- 이 5건은 최근 어느 배치에서도 성공한 적이 없다 (`logs/batch/*` 전수 확인 —
  마지막으로 돈 실전주행_교통류 는 `20260906_012222` 의 01·02 뿐).
- 실패 건은 `launch.txt` 자체가 안 생겼다 = `run_agent` 도달 전에 끊겼다.

**가설 (미검증)**: 이 5건은 경로가 3,000 m 대이고 교통류 객체가 많아 VTD 초기화가
120 s 예열 창을 넘긴다. `batch.warmup_s` 를 늘려 재시도해 볼 가치가 있다.

> **[6] 에서 이 가설이 뒤집혔다.** 02:38 에 같은 배치를 돌리자 **실경로_01·02 도
> 같은 오류**로 실패했다 — 00:01·23:31 에는 정상 주행했던 것들이다. 즉
> **시나리오 문제가 아니라 VTD 심 자체가 밤 사이 응답 불능이 됐다.**
> 02:44 확인: 48179·9910 **TCP 는 열려 있고** VTD 프로세스도 살아 있는데
> (`ps` 43건, load 4.1) 시나리오 로드 뒤 9910 으로 프레임이 안 나온다.
> 반복 Load/Start 누적으로 심이 잠긴 것으로 보인다 — **콘솔에서 재시작해야
> 한다.** → **아침 판단 필요 1 (수정됨).**

### ⚠ 이번 배치는 [1] 의 콘 변경이 **반영되지 않았다**

VTD PC 의 XML 은 **9/8 13:06** 자다 — 오늘 재생성한 XML(콘 1.0 m)은 로컬에만
있고 VTD PC 로 복사되지 않았다. 즉 위 두 완주는 **옛 콘 배치(0.3 m)** 결과다.
복사는 공용 장비에 쓰는 작업이라 임의로 하지 않았다. → **아침 판단 필요 2.**

### (a) 황색 신호 접근 전수

| 로그 | 황색전환 rs | 정지선까지 | 그때 속도 | 판정 | v / v_allow | 정지 slf | 침범 |
|---|---:|---:|---:|---|---|---:|---|
| 01 | 167.8 | 62.18 m | 24.6 km/h | stop | 6.83 / 26.9 | −1.21 | ok |
| 01 | 456.7 | 10.30 m | 19.6 km/h | stop | — | −0.10 | ok |
| 02 | 85.2 | 132.61 m | 44.3 km/h | stop | 12.32 / 32.32 | −0.26 | ok |
| 02 | 415.4 | 92.89 m | 24.2 km/h | stop | 6.72 / 26.96 | −2.39 | ok |
| **02** | **588.8** | **11.32 m** | **29.0 km/h** | **stop** | **8.06 / 8.62** | **+1.59** | **침범** |
| 02 | 675.1 | 70.23 m | 21.0 km/h | stop | 5.84 / 23.37 | −0.35 | ok |

**6건 중 1건 침범. 원인은 위상이 아니라 로직이다** — 지시안이 물은 그대로다.

`_yellow_latch` 는 `v ≤ √(2·a_yellow·d_eff)` 로 STOP/GO 를 정한다(`a_yellow=4.0`).
침범 건은 **v 8.06 vs v_allow 8.62 — 여유 0.56 m/s (7 %)** 로 아슬하게 STOP 이
나왔다. 그런데 이 식은 **판정 순간부터 −4.0 이 즉시 걸린다고 본다.** 실제로는
jerk 제한(`jerk_max 2.0 × jerk_dec_mult 3.0` = 0.3 m/s² per tick)이 있어
−4.0 도달에 **0.67 s** 걸리고, 그 사이 평균 감속이 절반이라
**약 v·t/2 = 8.06 × 0.67 / 2 ≈ 2.7 m** 를 더 간다.
여유 0.56 m/s 는 거리로 약 1.2 m 이므로 **부족분 ≈ 1.5 m** — 실측 침범
**+1.59 m** 와 맞는다.

다른 5건은 `v_allow` 여유가 3~4배라 이 오차가 묻혔다. **즉 근접 황색에서만
재현되는 계통 오차**다.

제안 (미적용): 판정 감속을 실효값으로 낮추거나(`a_yellow` 4.0 → 3.0),
`d_eff` 에서 jerk 램프 거리 `v²/(2·a) + v·a/(2·j_eff)` 를 빼고 재는 것.
전자가 한 줄이고 기존 상수 축과 같다. → **아침 판단 필요 3.**

### (b) 목표 속도 위인데 accel < −1.5 (급제동 회귀 재발 여부)

| 로그 | 구간 수 | 틱 | 전 주행 min accel |
|---|---:|---:|---:|
| 실경로_01 (신규) | **0** | 0 | −4.00 |
| 실경로_02 (신규) | 1 | 23 | −4.00 |

실경로_02 의 1구간은 rs 600.2~601.7 (min −3.90) 으로 **위 황색 침범과 같은
지점**이다 — 정지 프로파일이 정당하게 −4.0 을 쓴 구간의 jerk 잔량이라
[1] 회귀가 아니다. **실경로_01 은 0구간** (이전 11구간).

min accel −4.00 이 남아 있는 것은 정상이다 — 정지선·hazard 축은 안 건드렸다.

---

## [4] B3 적색 점멸 일시정지 (항목 9, 중대 −6)

### 채점기 — **이미 구현돼 있었다** (수정 없음)

지시안의 "미구현 표시 제거" 는 해당 없다. `tools/score.py` 의
`detect_blink_stop` ([:996](../tools/score.py#L996)) 이 이미:

- `ITEMS` 에 `(9, 'blink_stop', '적색점멸 일시정지')` 로 **키가 있고**
  (미구현 표시는 **항목 12 횡단보도 정차 금지**다 — 그쪽이 `key=None`),
- 범퍼 기준 `stop_line_front_m` 으로 `scoring.stop_ok_m`(2.0) 안 접근 +
  `stop_hold_s`(0.5) 이상 정지를 보고,
- 선을 **넘기 전**(`front_m ≤ 0`) 정지만 인정하며,
- 위반 등급이 `'major'`(중대) 다.

실측으로도 동작한다 — `logs/batch/20260902_201350` 두 로그 모두
**항목 9 = 1건 −6** 으로 이미 잡혀 있었다 (91/100). 즉 **채점은 맞고 제어기가
안 서던 것**이다.

### 제어기 — 고쳤다

| 파일 | 변경 |
|---|---|
| `vtd_adapter/carla_types.py` | `TrafficLightState.FlashRed = 5` 추가 |
| `vtd_adapter/route.py` | `LIGHT_STATE_MAP_FLASH` (6 → FlashRed), 스위치로 선택 |
| `team_code/kr_rules.py` | `_flash_tick` / `_flash_release`, `_stop_target_raw` 에 FlashRed, `signal_release` 에 합류 |
| `config/params.yaml` | `speed.signal_flash_stop_enable`(false) · `flash_hold_s`(0.8) |

**설계**: 6 → `FlashRed` 는 PDM 에 "녹색이 아닌 것" 이라 PDM 원문 비교문
(`== Red/Yellow/Green/Off`)이 전부 거짓이 되어 **손댈 필요가 없다**.
세우는 것은 `_stop_target_raw` 에 FlashRed 를 더해 **적색과 같은 ④′ 정지
프로파일 축**(`stop_profile_a`)으로 보낸 것이다 — 지시안대로 상한형이 아니다.
유지시간을 채우면 래치가 붙어 `_stop_target_raw` 가 None 이 되고 같은 틱에
`signal_release` 가 PDM 적신호 IDM 도 건너뛴다 = 재출발.

임계는 **새로 만들지 않았다** — `scoring.stop_ok_m` · `score.stop_speed_mps` 를
그대로 읽는다 (같은 주행이 제어기 기준과 채점 기준으로 갈리면 안 된다).

### 도중에 잡은 것 둘 (replay 로 드러남)

1. **PDM 의 적신호 IDM 만으로는 못 선다.** 처음에 매핑만 하고 돌렸더니 점멸
   정지선을 **5.4 m/s 로 통과**했다 (`red_light` 후보가 6.94 → 5.42 까지만
   내려간다). PDM 적신호 IDM 은 차간모형이라 정지 컨트롤러가 아니라는
   기존 주석 그대로다 → ④′ 를 태워야 했다.
2. **부호 규약 반전.** `d_line` 은 뒷축 기준 **남은 거리**(양수)인데
   로그·채점기의 `stop_line_front_m` 은 **음수 = 선 앞**이다. 처음에
   `front_m = d_line − front` 로 써서 판정이 통째로 뒤집혀 있었다.
   → `front_m = front − d_line` 로 채점기와 같은 축에 맞췄다.

### replay 실측 (적색점멸집중 2건, 스위치 on)

| 로그 | slf | 이전(off) | **수정(on)** |
|---|---:|---|---|
| 01_적색점멸 | −9.5 m | vt 6.94 · a +0.07 | vt 6.72 · **a −4.00** |
| 01_적색점멸 | −0.55 m | 무정차 통과 | **vt 0.00** (win=route_end) |
| 02_적색점멸23 | −8.0 m | — | vt 6.02 · **a −4.00** |
| 02_적색점멸23 | −1.17 m | 무정차 통과 | **vt 0.00** |

replay 는 **개루프**라 자차 궤적이 원본 그대로다 — 실제로 서지 않으므로
`hold_s` 가 0 에 머물고 재출발까지는 확인되지 않는다. **정지·유지·재출발
3단계는 단위 테스트로 검증**했다 (`tests/test_flash_red.py` 14건: 유지 0.8 s
→ 래치 → 정지 후보 소멸 → `signal_release` 참, 선 넘어 정지·원거리 정지·주행
중은 미인정, 래치가 다음 신호로 안 넘어감).

### 스위치는 **false** 로 둔다

`signal_flash_stop_enable: false` — 폐루프(배치) 검증 전이다. 실제로 서는지,
서고 나서 제때 출발하는지는 VTD 에서만 확인된다. → **아침 판단 필요 4.**

---

## [5] 작업 2 — 커밋 A (차로 지도, 읽기 전용)

`avoid_map.lane_map_avoid_enable` (기본 **false**).

자차 앞 `lane_map_ahead_m`(80 m)를 자차 차로 ±`lane_map_max_hops`(2) 범위에서
차로별로 재 둔다. **아무도 안 읽는다** — `reasons.lane_map` 진단으로만 나가고
후보 선택에 쓰는 것은 커밋 B 다.

| 필드 | 뜻 |
|---|---|
| `free_run[k]` | 그 차로 첫 **정지 객체**까지 거리. 없으면 80 |
| `passable[k]` | 존재 ∧ 같은 방향 ∧ 폭 ≥ 2 m ∧ 교차로 아님 |
| `blocked_by[k]` | 여유를 깎은 객체 id |
| `queue_dropped` | 큐로 빠진 객체 수 |

분석 (a)~(h) 에서 정한 대로 구현한 것:

- **객체 3점 투영** — 중심 + 좌우 폭 끝. 걸쳐 선 차가 두 차로를 다 막는다
  (증상 3). 객체에 차로 정보가 없다는 사실(로그 `lane: null` 은 설계)에 대한 답.
- **폭은 그 지점 보간값** — 평균이 아니다. 소멸 차로는 끝에서 0 이 된다.
- **큐 제외는 기존 규약 그대로** — `_tick_queue` 가 참인 틱에 `_tick_corridor`
  의 id 를 뺀다. 객체 단위 큐 판정을 새로 만들지 않았다 (억제 기준 두 벌 금지).
- **"정지 객체" 임계는 `overtake.blocker_speed_max`** 를 그대로 읽는다.

검증: `tests/test_lane_map.py` 15건 (이웃·여유·걸침·폭·교차로·큐 제외),
replay 56건 off 지문 **bit 동일**, pytest 1497 passed / 0 failed.

**커밋 B·C 는 하지 못했다** — 아래 참조.

### 커밋 B·C — **하지 않았다. 여기서 멈췄다.**

**막힌 것: 검증 수단이 없다.** 지시안이 B·C 의 합격 기준으로 못박은 것은
`tools/avoid_sim.py` 의 **10개 시뮬 케이스**(충돌 0 · |t_off| ≤ 0.6 · 조향 포화
0 · 지시등 방향 · 램프 시작 속도 ≤ 20)인데, **그 파일이 없다** — 새로 만들어야
한다. 횡·종 폐루프에 차선변경 램프까지 태우는 시뮬이라 그 자체가 큰 작업이고,
오늘 밤 안에 만들어 10 케이스를 다 태울 수 없다.

검증 없이 B 를 넣는 것은 **하지 않기로 판단했다**. 이유:

1. B 가 손대는 곳이 `_try_overtake_inner` 의 후보 선정과 `_side_pass` 의 side
   루프다 — 게이트 7개 · 2바퀴 · 래치 · 진단이 얽힌 저장소에서 가장 촘촘한
   코드다. 스위치가 false 라도 **켜는 순간 회피 전체가 그 경로**를 탄다.
2. 두 칸 램프는 `route.py` 의 `_shift_target_steps`(현재 "지금 있는 차로에서
   한 칸" 을 스스로 계산한다)에 **hop 수 인자**를 뚫어야 한다. PDM 이식부라
   회귀 범위가 넓은데, replay 지문으로는 **off 만** 검증되고 on 은 시뮬이
   있어야 검증된다.
3. C(복귀 없음)는 분석 (e) 에서 확인했듯 **기준 배열(`original_route_points` ·
   `_lat_build`) 교체 함수가 새로 필요**하고 지시등·속도캡·`_shift_target_steps`
   3곳이 그 기준을 공유한다. 하나라도 어긋나면 지시등이 역방향으로 켜진다
   (항목 13 감점). 이것도 시뮬 없이는 확인이 안 된다.

**남긴 것**: 커밋 A 의 차로 지도가 B 의 재료를 전부 만들어 두었고(`free_run` ·
`passable` · 3점 투영 · 큐 제외), 분석 (a)~(h) 에 **경계와 방법이 다 적혀 있다**.
B 를 이어서 하려면 순서는:

1. `tools/avoid_sim.py` — 10 케이스. 기존 `vtd_adapter` 플래너 + PDM
   `LateralPIDController` + 자전거 모델로 짤 수 있다 (실주행 1차 [2] 때 만든
   추종 시뮬과 같은 얼개).
2. `_shift_target_steps` 에 hop 수 인자 (기본값은 현행식 = 비트 동일).
3. `_lane_map_pick` (트리거·후보·선택·램프 역산) → `_side_pass` 의
   `target = lg.neighbor(...)` **한 줄만** 교체.
4. 감속 후보는 `cap_cand` 에도 넣는다 — 상한형이다 (CLAUDE.md 확정 사실).

→ **아침 판단 필요 5.**

---

## [6] 차로 지도 off 기준선 배치 — **못 돌렸다 (VTD 응답 불능)**

커밋된 상태(`4c92624`)로 `실경로_01`·`02` 2건을 돌리려 했으나 **둘 다
`VTD 9910 무응답`** 으로 실패했다 (`logs/batch/20260909_023829`).
위 [3] 각주 참조 — 심이 잠겼다.

**다만 기준선은 이미 있다.** [3] 의 두 완주가 오늘 밤 커밋들과 **같은 실행
경로**다:

- [1] 콘 여유는 VTD PC XML 에 반영되지 않았으므로 주행에 영향이 없다.
- [4] B3 는 `signal_flash_stop_enable: false`, [5] 커밋 A 는
  `lane_map_avoid_enable: false` — 둘 다 꺼져 있다.
- 그리고 **replay 56건 off 지문이 bit 동일**함을 확인했다 (아래 표).

즉 `실경로_01 완주 −15` · `실경로_02 완주 −15` 가 그대로 차로 지도 판단의
기준선이다. 심을 되살린 뒤 재확인만 하면 된다.

---

# 아침 요약

## 커밋 (시작 `7ede55a` → 끝 `4c92624`)

| 해시 | 단계 | 내용 |
|---|---|---|
| `a4c21bf` | [1] | 콘 여유 0.3 → 1.0 m, 21건 재생성 (경로 불변) |
| `02d203f` | [2] | CLAUDE.md 확정 사실 — `err/dt` 는 PDM IDM 전용 |
| `84868d0` | [3] | quick 배치 결과 + 황색 침범 원인 규명 (문서) |
| `f9d7318` | [4] | 적색 점멸 일시정지 (B3, 항목 9) — 기본 off |
| `a6278cf` | [5] | 차로 지도 커밋 A (읽기 전용) — 기본 off |
| `4c92624` | [5] | 커밋 B·C 중단 기록 (문서) |

## 회귀 검증 (최종 상태)

| 항목 | 결과 |
|---|---|
| pytest 전체 | **1497 passed / 2 skipped / 0 failed** |
| replay 56건 off 지문 | **56 / 56 bit 동일** (명령·목표속도·winner) |
| 실주행 배치 | [3] 에서 실경로 2건 완주, 이후 심 응답 불능 |

replay 지문 비교는 HEAD(`84868d0`) worktree 를 기준으로 같은 56쌍을 양쪽에서
돌려 대조했다. `logs/batch/*/routes/` 에 짝 pkl 이 있는 로그 전수다.

## 아침 판단 필요

1. **VTD 심이 잠겼다.** TCP 는 열려 있는데 로드 후 9910 프레임이 안 나온다.
   콘솔에서 재시작한 뒤 quick 7건을 다시 돌려야 [3]·[6] 이 완결된다.
2. **콘 여유 1.0 m 를 VTD PC 에 반영할지.** 재생성한 XML 은 로컬에만 있고
   VTD PC 는 9/8 13:06 자(0.3 m)다. 공용 장비에 쓰는 작업이라 임의로 복사하지
   않았다. 복사하지 않으면 [1] 은 검증용으로만 남는다.
3. **황색 판정의 jerk 보정.** `_yellow_latch` 의 `v_allow = √(2·a_yellow·d_eff)`
   가 판정 순간부터 −4.0 이 즉시 걸린다고 본다. 실제로는 jerk 제한으로 −4.0
   도달에 0.67 s 가 걸려 ~2.7 m 를 더 간다. 근접 황색에서만 드러나는 계통
   오차이고 실측 침범 +1.59 m 와 계산이 맞는다. 한 줄 고침 후보:
   `a_yellow` 4.0 → 3.0. **미적용.**
4. **B3 스위치를 켤지.** `signal_flash_stop_enable` — 단위 테스트로 정지·유지·
   재출발이 되고 replay 로 정지 프로파일이 걸리는 것까지 봤지만, **실제로
   서고 제때 출발하는지는 폐루프에서만** 확인된다. 심을 살린 뒤 적색점멸집중
   2건을 돌려 보고 켜는 것을 권한다.
5. **차로 지도 B·C 를 이어서 할지.** 막힌 이유와 이어서 할 순서는 위 [5] 참조.
   선행 작업은 `tools/avoid_sim.py` 10 케이스다.

## 스위치 현황표

오늘 밤 건드린 것과 관련 있는 것만.

| 키 | 값 | 비고 |
|---|---|---|
| `gen_placement.cone_margin_m` | **1.0** | [1] 변경 (0.3 → 1.0). VTD PC 미반영 |
| `control.cap_soft_dec_enable` | **true** | 실주행 2차 [1] (어제) |
| `control.cap_limit_target_enable` | **true** | 실주행 2차 [1] (어제) |
| `control.a_cap_dec_max` | −1.5 | 상한 추종 감속 클램프 |
| `speed.signal_flash_stop_enable` | **false** | [4] 신규 — 폐루프 검증 전 |
| `speed.flash_hold_s` | 0.8 | 규정 0.5 s + 여유 |
| `avoid_map.lane_map_avoid_enable` | **false** | [5] 커밋 A 신규 — 읽기 전용 |
| `avoid_map.lane_map_max_hops` | 2 | |
| `avoid_map.lane_map_ahead_m` | 80.0 | |
| `speed.finish_gate_ignore_enable` | true | 실주행 2차 [3] (어제) |
| `speed.curvature_cap_enable` | true | 실주행 1차 [2] |
| `route.banned_r_min_m` | 3.0 | 회전 금지 완화 (어제) |

**오늘 밤 새로 켠 스위치는 없다.** 신규 기능 둘([4] B3, [5] 차로 지도)은 전부
`false` 이고, 그래서 replay 56건 지문이 bit 동일하다.

---

# 아침 이어서 (09:00~)

## [1] a_yellow 4.0 → 3.0 · B3 스위치 on — 커밋 `352548f`

`a_yellow` 는 "판정 순간부터 −4.0 이 즉시 걸린다" 는 값이었다. jerk 제한
(0.3 m/s²/틱)으로 −4.0 도달에 0.67 s 가 걸리고 그동안 평균 감속이 절반이라
**v·t/2 ≈ 2.7 m (8 m/s)** 를 더 간다. 3.0 이면 실측 조건(d_eff 9.29 m, v 8.06)에서
`v_allow` 7.47 < 8.06 이라 **GO** 로 갈린다 — "설 수 없는데 서려다 걸치는" 것보다
낫다. `signal_flash_stop_enable` 도 true.

테스트 2건이 깨졌다 — `a_yellow` 와 `stop_profile_a` 가 우연히 같은 값(3.0)이
되어 **기본값 비교로 둘을 가르던** 검사다. 사본에서 `a_yellow` 만 올려
"판정은 따라가고 실행은 안 따라간다" 를 보게 고쳤다 (기본값이 또 움직여도
안 깨진다). jerk 지연분 반영 자체를 보는 검사도 추가했다.
**pytest 1498 passed / 0 failed.**

### 배치 — **7건 전부 실패. VTD Traffic 모듈이 안 붙는다.**

`logs/batch/20260909_091132` — 7건 전부 `VTD 9910 무응답 (120s 예열 초과)`.
황색·적색점멸 표는 **로그가 없어 만들 수 없다.**

원인을 특정했다:

```
tail /tmp/taskRec_TaskControl.txt   (VTD PC)
  NOTICE 09:29:44 (taskCtrl): "waiting for connection <Traffic>...."
  NOTICE 09:29:46 (taskCtrl): "waiting for connection <Traffic>...."
  ... (2 s 간격으로 무한 반복)
```

- **taskControl 이 Traffic 모듈 접속을 영원히 기다린다** → 시나리오가 시작되지
  않고 9910 으로 프레임이 안 나간다.
- 9910 은 TCP accept 는 되지만 **6 s 동안 0 B** (시나리오 무관하게).
- SCP(48179) Load 는 통과한다 — 그래서 batch_run 이 "로드는 됐는데 예열 실패" 로
  보인다.
- **simServer·taskControl 프로세스 ELAPSED 14:34** = 어제 18:55 부터다.
  재시작이 이 프로세스들에는 적용되지 않았다 (IG 등 다른 부분만 재시작된 듯).

→ **VTD 전체 스택을 다시 올려야 한다** (Traffic 모듈 포함). 그 전까지 배치는
전부 같은 자리에서 실패한다. 제어기 쪽 문제가 아니다.

---

# 이어서 (10:10~)

## [0] 콘 여유 1.0 → 2.0 m ✅

`gen_placement.cone_margin_m: 1.0 → 2.0`. `--from-yaml` 재생성 **20/21 성공**,
경로 CSV md5 집합 불변(콘 좌표만 이동).

**실경로_01_PathShape03 은 재생성이 안 된다** — 콘 여유와 무관한 경로 게이트다:

```
경로 게이트 탈락 — Path01 waypoint 구성 불가: Path01 첫/끝 waypoint 도로가
경로 시작/끝 도로와 다르다 (시작 또는 종점이 교차로 연결로 위인 경로)
```

`cone_margin_m` 을 1.0 으로 되돌려도 **같은 문구로 실패**한다(재현 확인). 즉
어젯밤 표의 01 행(+0.80)도 재생성물이 아니라 계산값이었다 — 디스크의 01 XML 은
**9/8 15:28** 자 그대로다. 01 의 종료점이 연결로 위라는 것은 실주행 2차 [3] 에서
"PathShape03 종료점을 직선 도로로 옮긴 CSV" 를 요구했던 것과 같은 사실이다.

회랑 여유 전수 (`finish_cone.finish_gate` 의 `clear_min` [m], 오름차순):

| 시나리오 | 0.3 | 1.0 | **2.0** | 차로폭 |
|---|---:|---:|---:|---:|
| 실경로_01_PathShape03 | +0.10 | +0.80 | **+1.80** | 2.40 |
| 실전주행_교통류_15_우회전25 | +0.27 | +0.97 | +1.97 | 2.75 |
| 실전주행_교통류_18_연속교차로14 | +0.27 | +0.97 | +1.97 | 2.75 |
| 실전주행_교통류_10_좌회전14 | +0.35 | +1.05 | +2.05 | 2.90 |
| 실전주행_교통류_17_직진6 | +0.37 | +1.07 | +2.07 | 2.94 |
| 실전주행_교통류_08_우회전16 | +0.38 | +1.08 | +2.08 | 2.97 |
| 실전주행_교통류_01_좌회전24 | +0.40 | +1.10 | +2.10 | 3.00 |
| 실전주행_교통류_05_직진24 | +0.42 | +1.12 | +2.12 | 3.04 |
| 실전주행_교통류_14_좌회전7 | +0.45 | +1.15 | +2.15 | 3.10 |
| 실전주행_교통류_04_직진2 | +0.50 | +1.20 | +2.20 | 3.20 |
| 실전주행_교통류_06_좌회전 | +0.51 | +1.21 | +2.21 | 3.23 |
| 실경로_02_venue0903 | +0.55 | +1.25 | +2.25 | 3.30 |
| 실전주행_교통류_16_직진20 | +1.95 | +2.64 | +3.62 | 0.75 |
| 실전주행_교통류_09_우회전13 | +2.97 | +3.67 | +4.67 | 3.08 |
| 실전주행_교통류_02_직진11 | +3.18 | +3.88 | +4.88 | 3.05 |
| 실전주행_교통류_12_연속교차로3 | +3.25 | +3.95 | +4.95 | 3.02 |
| 실전주행_교통류_11_직진10 | +3.31 | +4.01 | +5.01 | 3.03 |
| 실전주행_교통류_19_연속교차로11 | +3.70 | +4.40 | +5.40 | 3.20 |
| 실전주행_교통류_03_우회전11 | +4.20 | +4.90 | +5.90 | 3.00 |
| 실전주행_교통류_13_우회전11 | +4.20 | +4.90 | +5.90 | 3.00 |
| 실전주행_교통류_07_연속교차로8 | +6.39 | +7.09 | +8.09 | 3.34 |

| | 0.3 | 1.0 | **2.0** |
|---|---:|---:|---:|
| 최소 | +0.10 | +0.80 | **+1.80** |
| 중앙 | +0.51 | +1.21 | **+2.21** |
| 0.6 m 미만 | 12건 | 0건 | 0건 |

가장 좁은 경로(실경로_01, 폭 2.4 m 연결로)조차 **+1.80 m** 다. 이제 종료선을
못 지나면 그건 콘 때문이 아니다 — 원인 분리가 로그에서 끝난다.

---

## [1] 콘 회피 근본 수정 — 게이트를 **객체 위치** 기준으로 ✅

### 무엇이 틀렸었나

`_in_finish_gate` 가 **자차 route_s** 로 판정했다. 회피 시프트는 자차가 종료
구간에 들어오기 **훨씬 전에** 결정되므로 판정 시점이 구조적으로 늦다.

실측 `20260909_093415/실경로_02` — 콘 2개를 경로에 투영하면:

| | 값 |
|---|---|
| finish_s | 749.2 |
| 콘 id 2 · 3 의 **객체 route_s** | **749.2** (오차 0.0 m) |
| 시프트 생성 시점 | 자차 rs 690.9 (s_rel **58.3**) |
| 자차 기준 게이트(30) 가 열리는 곳 | rs 719.2 |

즉 게이트가 열리기 **28 m 전에** 이미 시프트가 만들어졌다. 자차 기준 게이트를
30 → 58.3 초과로 넓혀도 못 막는다 — **판정 축 자체가 틀렸다.**

### 고친 것 — 커밋 `974ad18` (이 절을 담은 커밋 자신)

1. **`finish_gate_by_object_enable`** (신규, true). 판정 기준이 객체의 route_s 다.
   투영은 전·후 범퍼까지 세 점을 보고 **가장 가까운** s 를 쓴다(보수적 — 게이트에
   걸쳐 선 물체는 계속 장애물로 본다). 임계는 `_finish_gate_s()` 한 곳이고
   회랑(`_corridor_blockers`)과 PDM 접합(`finish_gate_drop`)이 같은 값을 읽는다.
   `_in_finish_gate` 는 **off 경로 전용**으로만 남았다.
2. **`finish_gate_m` 30 → 10**. 30 이었던 이유는 자차 기준 판정 때문이었고
   (게이트가 늦게 열려 이미 선 뒤였다), 객체 기준에서는 그 이유가 통째로
   사라진다. 좁을수록 실제 장애물을 놓칠 여지가 준다.
3. **`span_lost_restore_enable`** (신규, true). 시프트를 만든 id 가 전부
   사라지면 그 자리에서 원복한다. 지금은 `route_index > span[1]` 뿐이라 span 끝이
   경로 끝 근처면 영원히 안 풀렸다 (02: span 끝 rs 776.0, 종료선 749.2).
   **"회랑이 비었다" 로 판정하면 안 된다** — 시프트 중에는 밀린 경로 기준 회랑에
   피한 물체가 안 들어와 항상 참이고, 그러면 모든 시프트가 즉시 원복돼 왕복이 된다.
   테스트 `test_active_shift_is_not_restored_while_the_target_is_there` 가 그 반례다.

### 검증

`실경로_02` replay (20260909_093415):

| | 기존 로그 | 수정 후 |
|---|---|---|
| 시프트 생성 | rs 690.9, span [7274,7760] | **0회** |
| avoid 상태 분포 | WAIT 59 · SHIFT_ACTIVE 333 · SHIFT_HOLD 356 | **전부 없음** |
| blocker (rs 690~751) | id 3 → None | 전 구간 None |
| `finish_gate.dropped` | 0틱 | **749틱** (자차 rs 669.5 = 감지창 80 m 진입 즉시부터, 콘 2 → 4) |
| v_target (rs 723~751) | **1.00 고정** (shift_cap) | 1.2~2.3 (route_end 프로파일) |

**replay 는 개루프**라 궤적은 못 바뀐다 — 여기서 증명되는 것은 "그 결정을 더는
하지 않는다" 까지다. 왕복·종료 횡오프셋·차로유지 감점은 VTD 배치에서 확인한다.

### off 지문 — 58/58 결정 동일

**방법을 고쳐야 했다.** 줄 순서 해시는 못 쓴다: `vtd_adapter/logger.py` 의
라이터 큐가 `maxsize=2000` 이고 replay 는 페이싱 없이 최대 속도로 도는 탓에
줄 유실이 비결정적이다 — **같은 코드·같은 설정으로 HEAD 를 두 번 돌렸더니
틱 수가 839 / 840 으로 갈렸다.** 어젯밤 "56/56 bit 동일" 은 운이 좋았던 것이다.

그래서 **자차 좌표를 키로** 한 결정 사전 비교로 바꿨다 (좌표는 재생 소스에서
오므로 두 실행이 같다). 이 잣대로 HEAD 자기 재현이 먼저 0 불일치를 냈고,

```
off 결정 동일 58 / 다름 0  (총 58)
```

키는 `(x, y, route_s)`, 값은 `(steering, accel, turn_signal, v_target, state, winner)`.

**pytest 1518 passed / 2 skipped / 0 failed.**

기존 `test_finish_gate_ignore.py` · `test_finish_gate_pdm.py` 는 **자차 기준 축의
계약**이므로 `on_cfg()` 에서 축을 명시적으로 고정했다 (두 축은 게이트가 열리는
시점이 다르므로 같은 rig 에서 같은 답을 낼 수 없다). 새 축의 계약은
`test_finish_gate_object.py` 12건, span 원복은 `test_span_lost_restore.py` 8건이
따로 본다.

---

## [2] 정지 프로파일·황색 판정의 jerk 램프 보정 ✅

### 아침 처방이 왜 틀렸나

아침에 `a_yellow` 4.0 → 3.0 으로 내렸다. **진단은 맞았고 처방이 틀렸다.**

- 지연분은 `v·t/2` 로 **속도에 비례**하는데, 상수를 내리면 저속 접근까지 똑같은
  비율로 보수적이 된다.
- 같은 지연이 **실행 축**(`stop_profile_a`)에도 있다. 판정만 고쳐서는 안 없어진다 —
  실제로 `20260909_093415` 에서 **정지선 침범 9건, 최대 +3.28 m** 가 그대로 났다.
- 그리고 `a_yellow` 3.0 = `stop_profile_a` 3.0 이 되어 **상수 두 개가 같은 일을**
  하게 됐다.

### 고친 것

`speed.stop_jerk_compensate_enable` (신규, true) 이 **판정·실행 두 축 모두**에서
거리를 깎는다:

    d_ramp  = v · (a / jerk_rate) / 2        jerk_rate = jerk_dec_mult × jerk_max = 6.0 m/s³
    v_allow = √(2·a·(d − s0 − d_ramp))

`jerk_rate` 는 **control 이 실제로 쓰는 두 상수를 그대로 읽는다** (새 상수 없음).
그리고 `a_yellow` 는 원래 의미("확실히 실행 가능한 최대" = `a_dec_max`)인
**4.0 으로 되돌렸다**.

### 검증 — 황색 판정이 정확히 속도에 따라 갈린다

`20260908_233155/실경로_02` replay, 황색 접근 4건 전수:

| rs | v | d_line | v_allow (기존 4.0) | v_allow (4.0+보정) | 판정 |
|---:|---:|---:|---:|---:|---|
| 85.2 | 12.32 | 136.41 | 32.32 | 31.81 (−1.6 %) | stop → **stop** |
| 415.4 | 6.72 | 96.69 | 26.96 | 26.63 (−1.2 %) | stop → **stop** |
| **588.8** | **8.06** | **15.09** | **8.62** | **7.27 (−15.7 %)** | stop → **GO** |
| 675.1 | 5.84 | 74.05 | 23.37 | 23.03 (−1.5 %) | stop → **stop** |

근접 황색 **하나만** 뒤집히고 여유 큰 3건은 그대로다. `a_yellow` 3.0 이었다면
4건 전부 13 % 씩 내려갔을 자리다 — 이것이 "상수를 깎는 것" 과 "거리를 보정하는 것"
의 차이다. (rs 588.8 은 아침에 기록한 **정지선 침범 +1.59 m** 를 낸 그 접근이다.)

### 검증 — ④′ 가 더 일찍·더 낮게 구속한다

`20260909_093415/실전주행_교통류_07` replay, 침범 4건 중 2건의 접근 곡선:

| 침범 rs | slf | v | 기존 v_target | 수정 v_target |
|---:|---:|---:|---:|---:|
| 870.8 | −13.98 | 10.48 | 8.33 (미구속) | **7.72 (구속)** |
| 870.8 | −8.56 | 9.35 | 6.25 | **5.77** |
| 870.8 | −4.43 | 6.88 | 3.81 | **2.65** |
| 1221.7 | −11.29 | 10.11 | 7.43 | **7.04** |
| 1221.7 | −7.27 | 9.07 | 5.59 | **4.80** |
| 1221.7 | −3.72 | 7.88 | 3.19 | **1.85** |

구속이 약 4 m 앞당겨지고 임계 지점에서 목표가 1.2~1.3 m/s 낮다.

**정지선 침범량 자체는 replay 로 못 잰다** — 개루프라 궤적(따라서 slf)이 로그
그대로다. 침범 0 여부는 VTD 배치에서 확인해야 한다. 다만 "정상 정지에서
과감속" 은 안 생긴다는 것이 구조적으로 보장된다: `d_ramp ∝ v` 라 v→0 에서
보정이 0 이 되고 계획 정지점이 안 움직인다 (`test_stop_point_does_not_move`).

### off 지문 · pytest

`[1]` 커밋 상태를 기준선으로 다시 뽑아 대조 — **58/58 결정 동일**.
**pytest 1532 passed / 2 skipped / 0 failed.**

`test_yellow.py` 2건을 고쳤다: (a) `v_allow()` 헬퍼가 보정을 **자기 축으로 다시
유도**하게 했다 (임계가 v 에 의존하므로 2차식 `v² + a·t·v − 2aD = 0` 을 푼다 —
코드 결과를 되읽는 것이 아니라 같은 물리를 독립적으로 푼 것이다).
(b) `test_a_yellow_accounts_for_the_jerk_ramp` 는 전제("a_yellow < a_dec_max")가
뒤집혔으므로 `test_jerk_ramp_is_compensated_by_distance_not_by_the_constant` 로
다시 썼다 — 보정이 속도에 비례하는지, 실측 조건이 GO 로 갈리는지를 본다.
새 파일 `test_stop_jerk_compensate.py` 14건이 보정식·두 축 적용·off 를 본다.

---

## [3] 우회전 차로 ✅ (a) 켬 · (b) 구현하고 기본 0 유지

### 지도가 직접 말해 준다 — 노면 화살표

`lanes[k]['arrows']` 가 있다. 비교차로 차로 **1773개 중 696개(39.3 %)** 가 갖고
있고(교차로 근처에만 있으니 필요한 곳엔 다 있다), 종류는
S 443 · SR 167 · L 143 · R 133 · SL 96 · LU 68.

이걸로 보면 07 의 증상은 "최우측이 아니다" 보다 훨씬 나쁘다:

| 경로 | 회전 | 진입 차로 | **화살표** | 남은 칸 | 연결로 |
|---|---|---|---|---|---|
| 07 s477.8 · 01 · 03 · 13 | **우회전** | (146,0,1) | **L** (좌회전 전용) | 우 1 | (1154,0,-2) 소멸 |
| 11 · 15 · 16 · 08 | 좌회전 | (2814,0,3) | **S** (직진) | 좌 1 | (3099,0,-3) |
| 02 · 14 | 우회전 | (2813,0,2) | **S** | 우 1 | (3096,0,-2) |
| 12 · 18 | 좌회전 | (2814,0,4) | SR | 좌 2 | (3099,0,-4) |
| 05 · 07 s666.5 | 좌회전 | (126,7,-2) | SSR | 좌 1 | (4728,0,-2) |

경로 34건 전수에서 **회전 차로 위반 19건**이다.

### (a) `taper_penalty_enable` false → **true** (켬)

| | 결과 |
|---|---|
| 바뀌는 경로 | **4 / 34** (01_좌회전24 · 03_우회전11 · 06_좌회전 · 13_우회전11) |
| 바뀌는 내용 | 전부 같은 자리 — junction 33 에서 `(1821,0,-2)` → `(1821,0,-3)` |
| `(1821,0,-2)` | 길이 29.7 m, **끝 폭 0.00 m** (차로가 완전히 사라진다) |
| `(1821,0,-3)` | 길이 30.2 m, 폭 2.71 → 3.00 m 유지 |
| 대가 | 경로당 **+1.2 m**. 차선변경 불필요 (successor 링크) |
| 회전 차로 위반 | 19 → **19** (이 스위치는 그 축이 아니다) |

명백한 개선이라 켰다. 나머지 30건은 점 하나 안 바뀐다.

**그리고 이것으로 07 은 안 고쳐진다** — 07 의 연결로 `(1154,0,-2)` 도 소멸
연결로(끝 폭 0.04 m)라 벌점 40 m 를 무는데도 그대로다. 대안이 차선변경을
요구하기 때문이다 (아래).

### (b) `route.turn_lane_bias_m` — 구현했고 기본 **0**

다음 짝이 우회전이면 진입 차로에서 **오른쪽에 남은 차로 수**만큼, 좌회전이면
왼쪽에 남은 수만큼 successor 진입 비용에 더한다.

| bias | 경로 변화 | 회전 차로 위반 | 총거리 합 Δ |
|---:|---:|---:|---:|
| **0** (기본) | 0 | 19 | +0.0 m |
| 5 | 0 | 19 | +0.0 m |
| 15 | 0 | 19 | +0.0 m |
| **30** | **5** | **14** | **−20.1 m** |

15 이하는 아무것도 안 바뀐다 — `LC_PENALTY`(25) 를 못 넘기 때문이다.
**30 은 위반 5건을 고치고 경로가 오히려 20 m 짧아진다** (바뀐 5건:
08_우회전16 · 11_직진10 · 15_우회전25 · 16_직진20 · pair_lane_offset).
길어지는 경로가 하나도 없다. 값은 사람이 정한다 — 지시대로 기본 0 으로 뒀다.

### (c) 07 은 왜 (b) 로도 안 고쳐지나 — **고쳐서도 안 된다**

```
   bias   0 →  연결로 (1154,0,-2)      총거리 3095.1
   bias  30 →  연결로 (1154,0,-2)      총거리 3095.1
   bias 100 →  연결로 (1154,0,-2)      총거리 3095.1
   bias 400 →  연결로 (1154,0,-3)      총거리 3086.8   ← 여기서야 뒤집힌다
```

대안 차로 `(146,0,2)` 는 **테이퍼로 열리는 차로**다:

- 길이 34.5 m, 시작 폭 **0.00** → 끝 2.40
- **차폭(1.886)이 되는 지점이 s 27.5** — 연결로까지 **7.0 m** 남는다
- 점선 구간은 s 21.0~34.5 (13.5 m)
- `LC_MIN_CORRIDOR_M`(25) 부족분 18 m × `LC_SHORT_PENALTY_PER_M`(20) = **360 m**

즉 DP 가 안 고른 것이 **옳다** — 7 m 에서 차선변경은 물리적으로 불가능하다.
bias 400 으로 억지로 뒤집으면 주행 불가능한 경로가 나온다.

**섹션 경계에서 새 차로로 안 옮겨 타는 것**((c) 질문)도 같은 답이다: 옮겨 탈
자리 자체가 7 m 뿐이라 별도 문제가 아니라 **이 지점의 지도 형상**이다.
`(146,1,1)`(111.8 m, 우이웃 없음) → `(146,0,1)` 이라 더 앞에서 옮겨 탈 기회도 없다.

**남는 선택지는 두 가지고 둘 다 사람 판단이 필요하다:**
1. `turn_lane_bias_m: 30` 으로 다른 5건을 고치고 07 은 남긴다 (권장).
2. 07 은 주최측 경유점이 만든 형상이라 경로에서 풀 문제가 아니라고 본다.

`pytest` 경로 계열 6파일 103 passed.

---

## [4] VTD Traffic — **이제 붙는다** ✅ (재시작으로 해결)

전제("배치가 전부 빈 도로였을 수 있다")는 **이번 배치에서 거짓**이다.
`20260909_093415` 의 `objects[]` 에 `cls: "vehicle"` 이 속도 4.7 · 8.3 m/s 로 들어 있다.

| 시나리오 | 배치 | **관측** | 차량 id | 보행자 |
|---|---:|---:|---:|---:|
| 실경로_02_venue0903 | 20 | **0** | 0 | 0 |
| 실전주행_교통류_07_연속교차로8 | 12 | **10** | 13 (움직임 12) | 0 |
| 실전주행_교통류_09_우회전13 | 12 | **11** | 10 (전부 움직임) | 1 |
| 실전주행_교통류_10_좌회전14 | 20 | **9** | 15 (움직임 14) | 0 |
| 실전주행_교통류_11_직진10 | 20 | **13** | — | — |
| 실전주행_교통류_18_연속교차로14 | 12 | **12** | 12 (전부 움직임) | 1 |

실경로_02 만 0대다 (경로가 배치 지점을 안 지난다 — 다른 5건이 다 보이므로
모듈 문제가 아니다). 09:11 배치의 전건 실패는 `taskControl` 이
`waiting for connection <Traffic>` 로 멈춰 있던 것이고, 사용자의 VTD 재시작으로
해소됐다.

**그래서 이번 배치가 정적 장애물·앞차 검증이 실제로 된 첫 배치다.**

`실경로_01` 만 여전히 별개로 죽는다 — 9910 **연결은 되는데 프레임이 0** 이다
(`gap_open` tick 20 → `gap` 무한). 다른 6건은 같은 VTD 에서 정상이므로 이건
**01 시나리오 자체의 문제**다. [0] 에서 확인한 "종료점이 교차로 연결로 위" 와
같은 뿌리일 가능성이 높다.

---

## [5] quick 7건 배치 결과 — `logs/batch/20260909_093415`

**완주 2 / blocked 4 / no-data 1 · 평균 감점 −10.5**

| 시나리오 | 상태 | 거리 [m] | 평균 [km/h] | 감점 | 주요 위반 |
|---|---|---:|---:|---:|---|
| 실경로_02_venue0903 | **완주** | 751.0 / 749.2 | 17.2 | −12 | 차선변경 |
| 실전주행_교통류_09_우회전13 | **완주** | 3002.6 / 3000.3 | 24.7 | −9 | 차선이탈 |
| 실전주행_교통류_07_연속교차로8 | blocked | 2821.9 / 3084.4 | 17.6 | **−21** | 차선이탈 |
| 실전주행_교통류_18_연속교차로14 | blocked | 2606.2 / 2999.8 | 18.7 | −9 | 적신호 |
| 실전주행_교통류_11_직진10 | blocked | 477.2 / 3137.4 | 26.9 | −9 | 적신호 |
| 실전주행_교통류_10_좌회전14 | blocked | 256.8 / 3104.1 | 11.2 | −3 | 적신호 |
| 실경로_01_PathShape03 | no-data | — | — | — | VTD 프레임 0 |

### ★ blocked 4건이 **전부 같은 모양**이다 — 최대 실점원

| 시나리오 | 멈춘 rs | 앞 장애물 | avoid 상태 |
|---|---:|---|---|
| 10_좌회전14 | 257.3 / 3104 | blocker 25 → 29, s_rel 20.9 | PREEMPT → **REACTIVE 고착** |
| 11_직진10 | 477.7 / 3137 | blocker 7, s_rel 20.1 | SHIFT_ACTIVE → BREAKOUT → **SHIFT_HOLD 고착** |
| 18_연속교차로14 | 2606.7 / 3000 | blocker 11, s_rel 22.0 | **SHIFT_HOLD 고착** |
| 07_연속교차로8 | 2822.2 / 3084 | blocker 6 | SHIFT_ACTIVE/HOLD/BREAKOUT/REACTIVE 순환, `reject=right:geom` **58 s** |

넷 다 **20~22 m 앞 정지 차량**, `v_target = 0`, 30 s 무전진으로 종료. 10 과 11 은
출발 1~2 분 만이다. 교통류가 처음으로 붙으면서 드러난 문제이고, **[6] 차로 지도
회피가 정확히 이걸 겨냥한 것**이라는 실증이다.

### (a) 회전 차로 검사 — 주행 로그 기준

| 시나리오 | 회전 | s | 자차 차로 | 좌/우 남은 칸 | 판정 |
|---|---|---:|---|---|---|
| 02 | turn_left | 221.8 | (429,0,2) | 0 / 4 | OK |
| 02 | turn_right | 363.1 · 512.2 | (420,2,-1) · (190,0,1) | 0 / 0 | OK |
| 02 | turn_right | 604.0 | (465,0,2) | 1 / 0 | OK |
| 07 | turn_right | 51.2 · 309.4 | (420,2,-1) · (174,0,1) | 0 / 0 | OK |
| 07 | turn_left | 200.4 | (190,0,1) | 0 / 0 | OK |
| **07** | **turn_right** | **477.8** | **(146,0,1)** | 0 / **1** | ✗ |
| **07** | **turn_left** | **666.5** | **(126,7,-2)** | **1** / 2 | ✗ |
| 07 | turn_right | 1585.7 · 1925.9 | (1926,5,-5) · (1868,0,3) | 4/0 · 1/0 | OK |
| 09 | 8건 전부 | — | — | — | OK |
| 10 | turn_left | 212.7 | (1910,0,-1) | 0 / 1 | OK |
| 18 | turn_left | 102.8 · 1198.6 | (2467,2,-1) · (3142,0,-1) | 0 / 1 | OK |
| **18** | **turn_left** | **2017.5** | **(2814,0,4)** | **2** / 0 | ✗ |
| 18 | turn_right | 2414.1 | (2675,0,4) | 2 / 0 | OK |

**주행 3건 위반.** 경로 전수(34건)에서는 19건 — [3] 참조.

### (b) 목표 속도 위인데 `accel < −1.5` 인 구간

| 시나리오 | 구간 수 | min accel |
|---|---:|---:|
| 실경로_01 | 0 | — |
| 실경로_02 | 1 | −2.67 (rs 721.4~723.3, winner=route_end — **콘 시프트 구간**) |
| 07 | 8 | −3.90 |
| 09 | 5 | −3.90 |
| 10 | 0 | — |
| 11 | 4 | −3.90 |
| 18 | 8 | −3.90 |

`winner` 가 `lead` · `light` · `route_end` · `none` 인 것들이라 **전부 정지 축**
(`err/dt` 가 정당한 축) 이다. 어제 고친 상한형(`cap_binds`) 축의 재발은 없다 —
곡률·LC 상한이 winner 인 구간은 0건이다. 02 의 1건은 [1] 로 사라진다.

### (c) 황색 접근 전수 — **30건**, `[2]` 적용 후 판정 뒤집힘 **0건**

로그는 `a_yellow` 3.0 · 보정 없음으로 돌았다. 30건 각각의 `d_eff` 를 역산해
새 방식(4.0 + jerk 보정)으로 다시 판정하면 **하나도 안 뒤집힌다** — 여유가
전부 크거나(+5 ~ +40 m/s) 이미 GO 다. 즉 이번 배치의 정지선 침범 9건은
**황색 축이 아니라 실행 축(④′)** 에서 나왔고, `[2]` 가 고친 것이 그쪽이다.

GO 5건: 07 rs 304.9(d_eff 0.00) · 654.7(5.90) · 1345.6(3.32),
10 rs 209.0(0.00), 18 rs 1171.7(20.87, 여유 −0.86 — 가장 아슬한 건).

### 정지선 침범 — **9건 / 22회 접근, 최대 +3.28 m**

배치 리포트 정지 지표 표 그대로. 침범 지점 접근 속도가 **43~49 km/h** 로
전부 몰려 있다 (`[2]` 의 근거).

| 시나리오 | route_s | slf [m] | 접근 [km/h] |
|---|---:|---:|---:|
| 07 | 870.8 | **+1.73** | 47.2 |
| 07 | 1221.7 | **+1.57** | 45.0 |
| 07 | 1582.6 | +0.85 | 43.9 |
| 07 | 2292.6 | **+1.49** | 49.0 |
| 18 | 713.1 | +1.45 | 44.3 |
| 18 | 1785.2 | **+3.28** | 47.1 |
| 18 | 2411.7 | **+1.51** | 47.1 |
| 09 | 161.2 | +1.35 | 47.7 |
| 11 | 320.6 | **+1.70** | 46.5 |

정상 정지 13건은 slf −0.46 ~ −3.14 (전부 선 앞). **저속 접근(20~36 km/h)은
한 건도 안 넘었다** — 속도 의존이 그대로 보인다.

### (d) 교통류 관측 — [4] 표 참조 (5/6 시나리오에서 9~13대)

### (e) 콘 게이트 · 종료 횡오프셋

| 시나리오 | 완주 | 최종 rs | 종료 시점 횡오프셋 | 콘 여유 | 종료 차로 |
|---|---|---|---:|---:|---|
| 실경로_02 | **완주** | 751.5 / 749.2 | +0.30 m | +2.25 | (418,2,**−2**) |
| 09_우회전13 | **완주** | 3003.0 / 3000.3 | −0.00 m | +4.67 | (2814,0,3) |
| 07 | 미완주 | 2822.2 / 3084.4 | −0.33 m | +8.09 | — |
| 10 | 미완주 | 257.3 / 3104.1 | −0.16 m | +2.05 | — |
| 11 | 미완주 | 477.7 / 3137.4 | −0.25 m | +5.01 | — |
| 18 | 미완주 | 2606.7 / 2999.8 | −0.11 m | +1.97 | — |

02 는 이번엔 **완주**했다 (지난 배치는 왕복하다 미완주). 다만 종료 차로가
계획한 `(418,2,−1)` 이 아니라 `−2` 다 — 콘 시프트가 남긴 것이고 `[1]` 이
고친 그 문제다. 콘 여유는 전 건 양수라 **콘이 원인인 정지는 이번에 0건**이다.

---

## [6] 차로 지도 — `tools/avoid_sim.py` 10케이스 기준선 (현행 코드)

무대: 실제 지도 road 3113 sec 0 (4차로 · 200 m · κ=0 직선 · 점선), 진입 8.33 m/s.
액터·신호는 **저장소 어댑터 타입 그대로** 쓴다 (`VtdActor`/`VtdEgo`/
`VtdTrafficLight`) — 스텁을 만들면 PDM 이 만지는 표면을 하나씩 빠뜨린다
(실제로 `get_actor`·`type_id` 에서 두 번 죽었다).

무대가 하나뿐이라 적신호(6)·실선(7)·다음 좌회전(8)은 **무대손질 콜백**으로
명시했다. 안 하면 셋 다 케이스 1 과 같은 상황이 되어 같은 답이 나온다
(처음 돌렸을 때 실제로 그랬다).

| # | 케이스 | 충돌 | \|t_off\| | 시프트 | 차로 | 최저 v | **정지 [s]** | 판정 |
|---|---|---:|---:|---|---|---:|---:|---|
| 1 | 단독 장애물 | 0 | 1.43 | 1회 p1 | −2,−1 | 5.90 | 0.0 | **OK** |
| 2 | **대회장: 1·2차로 나란히, 3차로 빔** | 0 | 1.43 | 1회 p1 | **−2,−1** | 0.00 | **25.1** | **✗ 3차로 못 감** |
| 3 | 엇갈림 | 0 | 1.43 | 1회 p1 | −2,−1 | 5.90 | 0.0 | OK |
| 4 | **걸쳐 선 차, 3차로 빔** | 0 | 1.43 | 1회 p1 | **−2,−1** | 0.00 | **23.1** | **✗ 3차로 못 감** |
| 5 | 연속 3대 30 m | 0 | 1.44 | 1회 p1 | −3,−2,−1 | 0.00 | **9.0** | **△ 9 s 정지** |
| 6 | 신호 대기 줄 (적색) | 0 | 0.00 | 없음 | −1 | 0.00 | 39.5 | **OK** (SUPPRESS) |
| 7 | 실선 구간 | 0 | 1.43 | 1회 **p2!** | −2,−1 | 5.90 | 0.0 | **의도된 동작** ↓ |
| 8 | 다음 좌회전, 우측 회피 | 0 | 1.43 | 1회 p2! | −2,−1 | 5.90 | 0.0 | 복귀 미확인 |
| 9 | 양쪽 다 막힘 | 0 | 1.43 | 1회 p2! | −2,−1 | 0.00 | 25.1 | OK (never_stall) |
| 10 | 먼 차로에만 장애물 | 0 | 0.00 | 없음 | −1 | 5.75 | 0.0 | **OK** |

`p{n}` = 몇 번째 바퀴에서 시프트했나, `!` = 실선 게이트를 건너뛰었다.
**on/off 는 전 케이스 동일하다** — 커밋 A 는 읽기 전용이므로 당연한 결과다.

### 케이스 7 은 버그가 아니라 **의도된 설계**다

`_side_pass` 의 `skip_solid = n_pass >= 2` (B-3): 1차 바퀴는 실선으로 기각하고,
2차 바퀴에서 실선을 넘는다. 실선 차로변경은 항목 6 **경미**인데 미완주는
훨씬 크기 때문이다. NIGHT 목록의 기대("시프트 안 함 → standoff")와 어긋나므로
**사람 판단이 필요하다** — 지금은 기존 설계를 그대로 뒀다.

### ★ 케이스 2·4 가 이번 배치의 blocked 4건과 **같은 모양**이다

둘 다 옆 차로(−2)로 한 칸만 시프트한 뒤 그 차로도 막혀 **23~25 초 정지**하고
never_stall 로 넘어간다. 3차로는 비어 있는데 못 간다. 배치에서 10·11·18·07 이
20~22 m 앞 정지 차량 앞에서 죽은 것과 정확히 같다.

**차로 지도(커밋 B)의 직접 근거다** — `lane_map_max_hops` 2 로 두 칸을 보고
`free_run` 이 가장 큰 차로를 고르면 케이스 2·4 가 3차로로 간다.

---

## [6] 커밋 B — 후보 선택·시점·감속 ✅ (스위치는 여전히 false)

### 먼저 — 커밋 A 에 버그가 **두 개** 있었고 테스트가 그걸 고정하고 있었다

`avoid_sim` 으로 실지도에서 처음 돌려 보고 드러났다. `lane_map` 의
`blocked_by` 가 **늘 비어 있었다** — free_run 이 항상 `ahead_m`(80) 이라
지도가 아무 정보도 주지 않았다.

| 버그 | 내용 |
|---|---|
| ① 좌표계 | `_actor_lanes` 가 `get_location()`(**CARLA**)을 `lg.locate`(**VTD**)에 그대로 넘겼다. `_ego_lane` 은 `frame.from_carla_xy` 를 거친다 |
| ② 필드명 | `LaneMatch` 의 차로 필드는 `.lane` 인데 `.key` 를 읽었다 (실지도에서는 `AttributeError`) |

`tests/test_lane_map.py` 의 목이 **CARLA y 를 그대로 받고 `.key` 를 돌려주도록**
쓰여 있어서 두 버그를 다 통과시켰다. 목을 실제 규약(VTD 좌표 · `.lane`)에 맞추고
그 근거를 목 docstring 에 남겼다. 15건 그대로 통과한다.

### 구현

| 항목 | 내용 |
|---|---|
| 트리거 | **내 차로** free_run < `lane_map_decide_m`(50). 다른 차로가 막힌 것은 트리거가 아니다 |
| 감속 | 트리거 즉시 `lane_map_avoid_speed_kph`(20) 상한 후보. **상한형이라 cap 축** (P + `a_cap_dec_max`, err/dt 금지 — CLAUDE.md 확정 사실) |
| 램프 길이 | 상수가 아니라 전이 기하에서 유도: `y = Y(1−cos(πx/L))/2` → `L = v·π·√(Y/(2a))`, `Y` = 칸 수 × 차로폭, `a` = **`overtake.a_lat_max` 그대로** (`_shift_speed_cap` 과 같은 축이라야 "만들 땐 되는데 지나갈 땐 상한에 걸린다" 가 안 생긴다) |
| 후보 | passable ∧ free_run > 램프 + `shift_ahead_m` |
| 선택 | free_run 최대 → 동률이면 hop 적은 쪽 |
| 시작 s | 첫 장애물 s − shift_ahead_m − 램프. 지났으면 **감속해 램프를 줄이고**, 크립보다 느려야 하면 후보 없음(standoff) |
| 개입 | ① min() 상한 후보 ② 시프트 **방향 힌트**(게이트 7개는 그대로) ③ `n_steps` |

**두 칸은 한 번에 연다.** 한 칸씩 두 번은 못 쓴다 — 옆 차로도 막혀 있으면
첫 전이가 끝나기 전에 standoff 가 세워 두 번째 칸으로 갈 기회가 영영 안 온다
(실제로 그렇게 짰다가 케이스 2·4 가 그대로 25 초 정지했다).
그래서 `vtd_adapter/route.py` 의 `shift_route_smoothly`/`shift_route_around_actors`
에 **`n_steps` 인자**를 열었다. None = 이전 동작이고, **인자를 조건부로만 넘겨**
off 에서는 호출 서명이 글자 그대로 같다 (목 플래너를 쓰는 테스트 173건이 그
서명을 흉내낸다).

### 시뮬 10케이스 on/off 대조

| # | 케이스 | off 정지[s] | **on 정지[s]** | off 차로 | **on 차로** | 충돌 | 포화 |
|---|---|---:|---:|---|---|---:|---:|
| 1 | 단독 장애물 | 0.0 | 0.0 | −2,−1 | −2,−1 | 0 | 0 |
| **2** | **대회장 1·2 막힘, 3 빔** | **25.1** | **0.0** | −2,−1 | **−3,−2,−1** | 0 | 0 |
| 3 | 엇갈림 | 0.0 | 0.0 | −2,−1 | −3,−2,−1 | 0 | 0 |
| **4** | **걸쳐 선 차, 3 빔** | **23.1** | **0.0** | −2,−1 | **−3,−2,−1** | 0 | 0 |
| 5 | 연속 3대 | 9.0 | 9.0 | −3,−2,−1 | −3,−2,−1 | 0 | 0 |
| 6 | 신호 대기 줄 | 39.5 | 39.6 | −1 | −1 | 0 | 0 |
| 7 | 실선 | 0.0 | 0.0 | −2,−1 | −2,−1 | 0 | 0 |
| 8 | 다음 좌회전 | 0.0 | 0.0 | −2,−1 | −2,−1 | 0 | 0 |
| 9 | 양쪽 다 막힘 | 25.1 | **27.4** | −2,−1 | −2,−1 | 0 | 0 |
| 10 | 먼 차로에만 | 0.0 | 0.0 | −1 | −1 | 0 | 0 |

**케이스 2·4 가 목표였고 25.1 s → 0.0 s, 23.1 s → 0.0 s 다.** 충돌 0·조향
포화 0 은 전 케이스 유지. 케이스 6(큐 억제)·10(트리거 아님)도 그대로다.

**나빠진 케이스 1건**: 9 (양쪽 다 막힘) 25.1 → 27.4 s. 지도가 후보를 재고
기각하는 만큼 never_stall 진입이 2.3 s 늦다. 어차피 갈 곳이 없는 배치라
결과(never_stall)는 같지만 **커밋 D 기준의 "off 대비 나빠진 케이스 0" 은 못 맞춘다.**

`|t_off|` 는 on 에서 1.42~1.45 다 (off 1.43~1.44). 커밋 D 기준의 0.6 은
**어떤 차로변경으로도 못 맞추는 값**이다 — 이 지표는 "지금 있는 차로 중심선까지"
라 전이 한복판에서 반드시 차로폭 절반(1.5)에 근접한다. off 도 1.43 이므로
의미 있는 잣대는 on/off 동률이고, 그건 만족한다.

### 회귀

- **off 결정 58/58 동일** (기준선 = [3] 커밋 상태).
- **pytest 1539 passed / 2 skipped / 0 failed.** 새 파일 `test_lane_plan.py` 20건.
- `test_taper.py::test_params_present_default_off` → `test_params_present` 로 고쳤다
  ([3] 에서 켰으므로 기본값이 꺼져 있는지 보면 안 된다. off 커버리지는
  `test_penalty_off_takes_the_taper_connector` 가 사본에서 명시적으로 끄고 본다).

---

## [6] 커밋 C — 복귀 없음 ✅ (스위치는 여전히 false)

### 새 기계를 만들지 않았다

"복귀 없음" 을 곧이곧대로 하면 경로 자체를 새 차로로 다시 그려야 한다
(`original_route_points` 재작성). 그 대신 **복귀 전이를 옮겼다**: 시프트 span 이
마지막 장애물 + `extra_after_m`(10 m) 에서 끝나 곧바로 되돌아오던 것을,
**데드라인**(다음 회전의 유효 차로로 돌아와 있어야 하는 지점)까지 민다.

    데드라인 = 세그먼트 끝 − max(transition_m, shift_k_s·v) − never_stall_turn_margin_m

재료는 route.pkl 의 `valid_entry_lanes` 하나이고, `never_stall` (c)
(`_ns_turn_lane_pending`) 와 **같은 식**을 쓴다 (상수 복제 금지).

**데드라인이 없는 세그먼트에서는 안 민다.** `target='finish'` 는 "제약 없음"
이라 경로 끝까지 밀게 되는데, 그건 span 이 영영 안 풀리는 [1] 의 버그를 다시
만드는 짓이다 (실경로_02: span 끝 rs 776, 종료선 749.2).

### 검증 — 복귀 지점이 실제로 밀린다

`avoid_sim` 케이스 8 (장애물 rs 60, 다음 좌회전 rs 150, 유효 차로 = 원래 차로):

| | 시프트 시작 rs | **원복 rs** | 정지 |
|---|---:|---:|---:|
| off | 28.3 | **92.9** | 0.0 s |
| **on** | 27.6 | **142.4** | 0.0 s |

142.4 ≈ 150 − 전이(12) − 여유(10). 즉 **데드라인까지 옆 차로에 머물고**, 회전
전에 정확히 돌아온다. 지시등도 한 쌍만 쓴다(항목 13).

`test_lane_plan.py` 에 7건 추가 (데드라인 식 · `finish` 제외 · 미루는 거리 ·
off · 데드라인이 이미 가까울 때 안 미룸 · 계획 없을 때 관여 안 함).

**off 결정 58/58 동일** (기준선 = 커밋 B off 상태).
**pytest 1566 passed / 2 skipped / 0 failed.**

`reasons.avoid.lane_plan` 진단도 붙였다 — 스위치가 꺼지면 키가 안 생긴다
(실경로_02 off replay 에서 `lane_plan` 0건, 결정 동일 확인).

---

## [6] 커밋 D — **하지 않았다. `lane_map_avoid_enable` 은 false 그대로다**

지시안의 다섯 기준을 하나씩 댄 결과다.

| # | 기준 | 결과 | 근거 |
|---|---|---|---|
| 1a | 시뮬 10케이스 충돌 0 | **통과** | 전 케이스 0 |
| 1b | 조향 포화 0 | **통과** | 전 케이스 0 |
| 1c | 지시등 방향 맞음 | **통과** | 시프트한 8케이스에서 나감·복귀 한 쌍, 6·10 은 0건 |
| 1d | `\|t_off\| ≤ 0.6` | **미달 (지표 정의상 불가)** | on 1.42~1.45 / **off 도 1.43~1.44** |
| 1e | 램프 시작 속도 ≤ 20 km/h | **미달** | 실측 **24.6 km/h** (케이스 5 만 18.4) |
| 1f | off 대비 나빠진 케이스 0 | **미달** | 케이스 9 정지 25.1 → **27.4 s** |
| 2 | 07 rs 2822.2 갇힘 해소 | **증명 불가** | replay 는 **개루프** — 궤적이 로그 그대로다 |
| 3a | replay 58건 off 지문 동일 | **통과** | 58 / 58 |
| 3b | on 에서 새 standoff·크래시 0 | **미확인** | on 폐루프 배치를 안 돌렸다 |
| 4 | pytest 0 failed | **통과** | 1566 passed / 0 failed |

### 미달 항목의 성격

**1d 는 기준 자체가 못 맞추는 값이다.** `|t_off|` 는 "지금 있는 차로 중심선까지"
라 차로변경 전이 한복판에서 반드시 차로폭 절반(1.5 m)에 근접한다 — off 도
1.43 이다. 의미 있는 잣대는 **on/off 동률**이고 그건 만족한다. 기준을
"off 대비 +0.1 m 이내" 로 바꾸는 것이 맞다고 본다 (판단 필요).

**1e 는 진짜 미달이고 고칠 수 있다.** 트리거(free_run < 50 m)에서 시프트
생성까지 17.6 m 를 가는데, 상한 추종 감속(`a_cap_dec_max` −1.5, P 게인 0.8)이
8.33 → 5.56 m/s 를 만드는 데 그보다 더 필요하다. `lane_map_decide_m` 을
50 → 70 쯤으로 올리면 맞는다. **값은 사람이 정할 일이라 손대지 않았다.**

**1f 케이스 9(양쪽 다 막힘)는 2.3 s 손해다.** 지도가 후보를 재고 기각하는
만큼 never_stall 진입이 늦다. 결과(never_stall)는 같지만 기준은 "0" 이다.

**2 가 결정적이다.** 지시안은 이 케이스를 "차로 지도의 직접 근거 — 안 풀리면
on 하지 말 것" 이라고 못박았는데, **replay 로는 원리상 증명할 수 없다**
(개루프라 자차 궤적이 로그 그대로다). 대신 **결정이 달라지는 것**은 보였다:

```
rs 2814.2  ego_lane (2076,3,3)  내 차로 free_run 13.4 m  ← 트리거
           후보 (2076,3,2) free 80.0 / (2076,3,4) free 80.0
           pick (2076,3,4)   ← 지도는 탈출구를 본다
현행 코드   같은 자리에서 reject=right:geom  → 58 초 갇힘 → 미완주
```

**양옆이 둘 다 80 m 비어 있는데 현행 코드는 기하 게이트로 기각한다.**
차로 지도는 그걸 본다. 다만 rs 2820 이후 976틱은 `ramp_too_late` 다 — 이미
13 m 앞에서 정지한 뒤라 어떤 램프도 안 들어간다. **늦게 발견하는 문제는
남아 있고, 그게 1e 와 같은 뿌리다** (트리거를 더 앞으로).

### 그래서

**on 하려면 VTD 폐루프 배치 한 번이 필요하다.** 그건 [6] 지시안이 "on 으로
커밋했으면 quick 7건을 on 으로 한 번 더" 라고 한 그 배치인데, 순서가
뒤집혀야 한다 — **on 커밋 전에** 돌려야 2 와 3b 를 판정할 수 있다.
지금 상태로는 켤 근거가 모자라 **false 로 두고 멈춘다** (지시안대로).

---

# 아침 보고 (이어서 끝까지 — 10:10~)

## 커밋

| 해시 | 단계 | 내용 | 스위치 |
|---|---|---|---|
| `e84651a` | [0] | 콘 여유 1.0 → **2.0 m**, 21건 재생성 (20/21) | — |
| `974ad18` | [1] | 종료 게이트를 **객체 위치** 기준 + 시프트 대상 상실 원복 | **on** |
| `a6fc37b` | [2] | 정지 프로파일·황색 판정 **jerk 램프 보정**, a_yellow 4.0 복귀 | **on** |
| `4689026` | [3] | 소멸 연결로 벌점 **on** + `turn_lane_bias_m` 신규 | 벌점 on / bias 0 |
| `d99f94e` | [4][5] | Traffic 접속 확인 · quick 7건 배치 결과 5개 표 | — |
| `3666bbd` | [6] | `avoid_sim` 10케이스 완성 (무대손질·진단 열) | — |
| `b234944` | [6] | 차로 지도 **커밋 B** (+ 커밋 A 버그 2개 수정) | off |
| `f925ef9` | [6] | 차로 지도 **커밋 C** | off |
| `bd988d2` | [6] | 커밋 D 판정 — **하지 않음** | — |

**pytest 1566 passed / 2 skipped / 0 failed.** replay off 지문은 단계마다 새로
기준선을 뽑아 대조했고 전부 **58 / 58 결정 동일**이다.

## 방법론에서 하나 고쳤다 — 지문 비교

줄 순서 해시는 **못 쓴다**. `vtd_adapter/logger.py` 의 라이터 큐가
`maxsize=2000` 인데 replay 는 페이싱 없이 최대 속도로 돌아 줄 유실이
비결정적이다 — **같은 코드·같은 설정으로 HEAD 를 두 번 돌렸더니 틱 수가
839 / 840 으로 갈렸다.** 어젯밤 "56/56 bit 동일" 은 운이 좋았던 것이다.

지금은 **자차 좌표를 키로** 한 결정 사전 비교를 쓴다 (좌표는 재생 소스에서
오므로 두 실행이 같다). 키 `(x, y, route_s)`, 값
`(steering, accel, turn_signal, v_target, state, winner)`. 이 잣대로 HEAD
자기 재현이 먼저 0 불일치를 낸다.

## 판단이 필요한 것 (내가 안 정한 것)

1. **`route.turn_lane_bias_m`** — 0(현재) / 5 / 15 / 30. **30 이면 회전 차로
   위반 19 → 14, 총거리 −20.1 m** (길어지는 경로 0). 15 이하는 변화 0이다.
2. **07 s477.8 우회전** — (a)(b) 어느 쪽으로도 못 고치고 **고쳐서도 안 된다**
   (대안 차로가 7 m 뿐이라 물리적으로 차선변경 불가). 주최측 경유점이 만든
   형상으로 볼지 결정 필요.
3. **`avoid_map.lane_map_decide_m` 50 → 70?** 커밋 D 기준 1e(램프 시작 속도
   ≤ 20 km/h)가 실측 24.6 으로 미달인데, 트리거를 앞당기면 맞는다.
4. **커밋 D 기준 1d(`|t_off| ≤ 0.6`)** — 어떤 차로변경으로도 못 맞추는 값이다
   (off 도 1.43). "off 대비 +0.1 m 이내" 로 바꾸는 것이 맞다고 본다.
5. **차로 지도 on 판정용 VTD 폐루프 배치** — 순서가 뒤집혀야 한다. on 커밋
   **전에** quick 7건을 on 으로 돌려야 커밋 D 기준 2·3b 를 판정할 수 있다.
6. **avoid_sim 케이스 7(실선)의 기대** — 현행 `skip_solid`(n_pass ≥ 2, B-3)는
   2차 바퀴에서 실선을 넘는다. 지시안 기대("시프트 안 함")와 어긋난다.
   실선 차로변경은 항목 6 **경미**, 미완주는 훨씬 크다 — 지금 설계가 맞다고
   보지만 확인 필요.
7. **실경로_01** — VTD 에서 연결은 되는데 **프레임 0** 이고, 생성기에서도
   "종료점이 교차로 연결로 위" 로 재생성이 안 된다. 둘이 같은 뿌리로 보인다.

## ★ 가장 큰 실점원 (새로 드러난 것)

교통류가 **처음으로 실제 접속된** 배치(`20260909_093415`)에서 quick 7건 중
**4건이 전부 같은 모양으로 죽었다**: 20~22 m 앞 정지 차량, `v_target = 0`,
30 s 무전진. 10 과 11 은 출발 1~2 분 만이다.

`avoid_sim` 케이스 2·4 가 같은 상황이고, **커밋 B 가 25.1 s → 0.0 s,
23.1 s → 0.0 s 로 푼다.** 지금 켜지 못하는 이유는 위 5번(폐루프 확인) 하나다.

## 스위치 현황표

| 키 | 값 | 비고 |
|---|---|---|
| `gen_placement.cone_margin_m` | **2.0** | [0] (1.0 → 2.0). VTD PC 미반영 |
| `speed.finish_gate_ignore_enable` | true | 어제 |
| `speed.finish_gate_by_object_enable` | **true** | **[1] 신규** |
| `speed.finish_gate_m` | **10.0** | [1] (30 → 10) |
| `overtake.span_lost_restore_enable` | **true** | **[1] 신규** |
| `speed.stop_jerk_compensate_enable` | **true** | **[2] 신규** |
| `speed.a_yellow` | **4.0** | [2] (3.0 → 4.0 복귀) |
| `speed.stop_profile_a` | 3.0 | 불변 |
| `route.taper_penalty_enable` | **true** | **[3] (false → true)** |
| `route.turn_lane_bias_m` | **0.0** | [3] 신규 — **끔. 값은 사람이 정한다** |
| `avoid_map.lane_map_avoid_enable` | **false** | 커밋 A·B — **D 미달로 유지** |
| `avoid_map.lane_map_no_return_enable` | **false** | **커밋 C 신규 — 유지** |
| `avoid_map.lane_map_max_hops` | 2 | |
| `avoid_map.lane_map_ahead_m` | 80.0 | |
| `avoid_map.lane_map_min_width_m` | 2.0 | |
| `avoid_map.lane_map_decide_m` | **50.0** | 커밋 B 신규 (70 검토 — 위 3번) |
| `avoid_map.lane_map_avoid_speed_kph` | **20.0** | 커밋 B 신규 |
| `speed.signal_flash_stop_enable` | true | 아침 [1] |
| `speed.curvature_cap_enable` | true | 실주행 1차 |
| `control.cap_soft_dec_enable` | true | 실주행 2차 |
| `control.cap_limit_target_enable` | true | 실주행 2차 |
| `route.banned_r_min_m` | 3.0 | 회전 금지 완화 |

**오늘 새로 켠 것은 4개다**: `finish_gate_by_object_enable` ·
`span_lost_restore_enable` · `stop_jerk_compensate_enable` ·
`taper_penalty_enable`. 넷 다 off 지문 58/58 동일이 확인됐다.
차로 지도(커밋 A·B·C)는 **전부 false** 다.

## 경계 요청

- 대상: `tools/gen_scenarios.py` (실경로_01 경로 게이트), `config/params.yaml`
  의 `gen_placement.cone_margin_m` · `route.taper_penalty_enable` ·
  `route.turn_lane_bias_m`, `tools/build_route.py`
- 필요한 변경: [0] 콘 여유 2.0, [3] 소멸 연결로 벌점 on + `turn_lane_bias_m` 구현
- 이유: 지시안이 이 세션에서 명시적으로 요구한 작업이라 그대로 했다.
  기본 세션은 제어기 파트이므로 **사후에 남긴다**.
- 우회 여부: 불가 — [0][3] 은 정의상 생성기·경로 조립 쪽 작업이다.

---

# 회전 차로 제약 + 2차 주행 4건 (18:00~)

## [1] 회전 차로를 **제약**으로 ✅

### 지시안의 전제가 틀렸다 — laneLink 로는 못 만든다

지시안은 "junction connection 의 laneLink 로 차로별 허용 회전 집합을 만들어
후보 필터로 쓰라" 였다. 만들어서 대 보니 **19건 중 한 건도 안 걸린다.**

실측 (진입 차로 552개, 노면 화살표 보유 472개 = 85.5 %):

| | 건수 |
|---|---:|
| laneLink == 화살표 | 327 |
| **laneLink 가 더 관대** | **69** |
| 화살표가 더 관대 | 76 |

위반 10건을 표본으로 대 보면 **전부 laneLink 에는 그 회전이 있다**:

| 진입 차로 | 요구 | laneLink turn_set | **노면 화살표** |
|---|---|---|---|
| (146,0,1) | right | L·R·S | **L** (좌회전 전용) |
| (2814,0,3) | left | L | **S** (직진) |
| (2802,0,-1) | left | L | **R** (우회전) |
| (2813,0,2) | right | R | **S** |
| (126,7,-2) | left | L·S | **S·SR** |

지시안의 "우회전 진입 157건 전부 최우측에서 가능" 은 **가능성**의 진술이라
맞다 — 다만 그것이 "안쪽 차로는 못 한다" 를 뜻하지는 않는다. 지도의 연결은
노면 표시보다 관대하다.

**그래서 제약의 재료는 `lanes[k]['arrows']` 다.**

### 구현

`route.turn_lane_constraint_enable` (신규). dijkstra 의 successor 확장에서
연결로의 회전 방향이 진입 차로의 화살표에 없으면 **후보에서 제외**(continue)한다.

**안전망**: 같은 방향 이웃 중 그 회전 화살표를 가진 차로가 **하나도 없으면**
막지 않는다. 지도의 데이터 공백이라(실측 26개 접근로) 막으면 경로가 통째로
불가능해진다.

### (c)(d) 검증 — 경로 38건 전수 재빌드

| | off | **on** |
|---|---:|---:|
| 빌드 실패 | 0 | **0** |
| 기하 기준 회전 차로 위반 | 19 | **3** |
| 화살표 기준 위반 | 31 | **13** |
| 총거리 합 | 71144.9 m | **71060.4 m (−84.5)** |
| 경로 변화 | — | 16 / 38, **길어진 경로 0** |

(실패로 보였던 4건 — `dp_01` · `dp_02` · `dp_07` · `test_route_waypoints` — 은
**홀수 경유점 CSV** 라 짝 해석 대상이 아니다. 제약 off 에서도 똑같이 건너뛴다.)

**남는 위반은 전부 안전망이 작동한 자리다** — 접근로에 그 회전 화살표를 가진
차로가 하나도 없다:

| 진입 차로 | 요구 | 같은 방향 차로 | 화살표 |
|---|---|---|---|
| (190,0,1) | R | **1개(자기뿐)** | L |
| (310,0,1) | R | 1개 | S |
| (1777,0,2) | R | 2개 | S / L |
| (2802,0,-1) | L | 2개 | R / 없음 |

지도의 표시와 연결이 서로 어긋나는 결함이라 경로 탐색이 고칠 수 없다.

**`turn_lane_bias_m` 은 0 으로 유지한다** — 제약이 대체한다.

### 07 이 실제로 고쳐진다

```
before  (146,1,1) → (146,0,1) → (1154,0,-2)   화살표 L 에서 우회전, 끝 폭 0.04 m
after   (146,1,1) → (146,0,1) → (146,0,2) → (1154,0,-3)   화살표 SR, 폭 유지
        좌회전도 (126,7,-2) → (126,7,-1) (화살표 L)
        총거리 3095.1 → 3086.8 m
```

### 정정 — "물리적으로 불가능" 은 내 오독이었다

아침에 "(146,0,2) 는 7 m 뿐이라 차선변경이 물리적으로 불가능하다" 고 적었다.
**7.0 m 는 차폭 기준이고, 차선변경이 허용되는 점선 구간은 s 21.0~34.5 = 13.5 m 다.**
13.5 m 전이는 `L = v·π·√(Y/2a)` 로 **v ≤ 4.3 m/s (15 km/h)** 면 들어간다 —
우회전 접근 속도라 무리가 아니다.

**판단 필요**: `speed.lc_speed_cap_kph` 가 20 km/h 인데 그 속도면 전이가
17.5 m 필요해 13.5 m 를 넘는다. 이 자리에서만 더 낮춰야 할지, 곡률 감속
(`curvature_cap`)이 연결로 진입에서 이미 낮추므로 충분한지는 폐루프로 봐야 한다.

`pytest` 경로 계열 8파일 118 passed + 제약 테스트 6건 신규.

---

## [2] 2차 주행 문제 4건 ✅ (A 는 [1] 소관, B·C·D 수정)

### (A) 1차로에서 우회전 — **경로 문제, 회피 아님**

두 배치 전수에서 회전 지점의 시프트 상태를 봤다:

| 배치 | 회전 | s | 자차 차로 | 화살표 | **시프트 중** |
|---|---|---:|---|---|---|
| 093415 | turn_right | 477.8 | (146,0,1) | L | **False** |
| 093415 | turn_left | 666.5 | (126,7,-2) | S·SR | **False** |
| 093415 | turn_left | 2017.5 | (2814,0,4) | SR | **False** |
| 174746 | turn_right | 477.8 | (146,0,1) | L | **False** |

**전부 시프트 중이 아니다** — 경로가 그 차로를 지정했고 차는 정확히 따랐다.
[1] 의 화살표 제약은 셋 다 걸러내지만(19 → 3) rc≠0 이 늘어 **켜지 못했다**
(아래 [1] 정정 참조). `turn_lane_bias_m: 60` 이 위반을 19 → 12 로 줄인다.

### (B) 지시등 미점등 — **가설이 틀렸고 원인은 우선순위 충돌**

지시안은 "소멸 차로 인계를 `_lane_shift` 가 못 본다" 였다. 데이터가 반박한다 —
그 전환에서 `src=lc` 로 켜졌으니 `lat_shift` 는 인계를 **본다**.
(가설대로 만들었던 `_lane_handover` 구현은 되돌렸다.)

채점기가 잡은 4건의 정체:

| 위치 | 전환 | on_s | 정체 |
|---|---|---|---|
| 02 s 647.0 | (418,0,-4) → (418,0,-3) | **1.5 s** | 소멸 차로 인계 — 점등이 늦다 |
| 02 s 727.3 / 735.1 | (418,2,-2) ↔ -1 | None | 콘 시프트 왕복 — **[1] 이 이미 제거** |
| 07 s 2811.3 | (2076,3,2) → -3 | None | BREAKOUT 횡이동 |

첫 건의 실제 원인:

```
rs 600~638  sig=2 (RIGHT)  src=turn   ← 우회전 연결로를 도는 중
rs 638.1    sig=1 (LEFT)   src=lc     ← 연결로가 끝나야 비로소 켜진다
rs 647.2    경계 통과                  ← 9.1 m (≈1.5 s) 뿐
```

회전 지점을 지나면 `remain = max(0, 음수) = 0` 이라 **회전이 무조건 이긴다**.
그래서 반대 방향 지시등이 아예 못 켜진다.

**수정** `signal.signal_turn_tail_yield_enable` — 회전 지점을 지난 **꼬리**는
반대 방향 차로 이동에 양보한다. 채점 항목 13 은 **차로 변경** 지시등만 보므로
양보로 잃는 것이 없다. 같은 방향이면 양보하지 않는다.

**검증**: 좌측 최초 점등 rs 638.1 → **622.2**, 선행거리 9.1 m → **25.0 m**
(≈4.2 s > `scoring.signal_lead_s` 3.0).

### (C) 정지선 앞 찔끔찔끔 — **원인 둘 다 실재**

| 원인 | 실측 |
|---|---|
| PDM red IDM 이 **가속을 요구** | 02 적색 접근 667틱 중 **290틱(43.5 %)** 목표 > 현재속도, 최대 **+4.17 m/s** (slf −14.7 에서 v 5.44 인데 목표 6.15 → accel +0.57) |
| 정지 후 **미세 전진** | 02 정지 3회 중 2회, 07 5회 중 2회에서 v > 0.1 |

`_stopline_profile` 주석이 예고한 그대로다 — ④′ 는 √ 프로파일이라 그 구간에서
아직 v 위에 있어 min() 에서 진다.

**수정 둘**
- `speed.no_accel_toward_red_enable` — 정지 대상이 `red_lookahead_m`(60) 안이면
  목표를 현재 속도로 덮는다. **상한형이라 cap 축**(err/dt 금지).
- `speed.stopline_creep_latch_enable` — 정지 대상이 살아 있는 동안 목표 0 유지.
  녹색이 되면 대상이 사라져 저절로 풀린다(출발 지연 0).

**검증** (replay, `-30 ≤ slf ≤ 0` ∧ 적색):

| | 가속 요구 틱 | **accel 부호 전환** | 정지 중 목표>0 |
|---|---:|---:|---:|
| 02 off | 290 | **28** | — |
| **02 on** | **34** | **1** | — |
| 07 off | 234 | **36** | 110 / 1667 |
| **07 on** | **61** | **10** | **46 / 1667** |

남은 34틱은 **RTOR(적색 우회전) 출발**이라 정상이다 (`rtor.state="go"`,
채점기도 "적신호 우회전(정보) stopped_before=True" 로 기록).

### (D) 연속 장애물 blocked — **뿌리는 황색 래치와 PDM hazard 였다**

지시안의 가설 둘을 먼저 확인했다:

| 확인 항목 | 결과 |
|---|---|
| 복귀 중 새 시프트를 못 만드나 | **참** — 11: rs 389.8 시프트(blocker 4) → 400 회피 → **rs 431.6 새 blocker 7 (s_rel 66.3)** 인데 `ot_span` 활성이라 생성 건너뜀. 18 도 같은 꼴(2517.3 → 2560.3) |
| `_chain` 이 A·B 를 왜 안 묶었나 | 간격 **~54 m** ≫ `chain_gap_m` 22 |
| never_stall 이 왜 안 떴나 | **아래가 진짜 원인** |

`_obstacle_cause` 분기를 계측했다 (11 정지 1635틱):

```
('traffic_light_hazard', False): 1167    ← 여기서 죽는다
('TRUE', True):                   468
```

그리고 그 위에 황색 래치가 하나 더 있었다:

| | 황색 STOP 래치 d_line | 장애물 |
|---|---:|---:|
| 11 rs 477.7 | **150.8 m** | 20.1 m |
| 18 rs 2590.5 | **317.3 m** | 22.0 m |

**황색 판정에 거리 한계가 없어** 300 m 밖 황색이 STOP 을 래치하고, 그 래치가
`_obstacle_cause` 를 거짓으로 만들어 **크립·BREAKOUT·never_stall 을 전부 죽인다.**
PDM 의 `traffic_light_hazard` 도 같은 일을 한다 — 정지선이 150 m 밖인데 20 m 앞
정지 차량에 막힌 것까지 신호 대기로 분류한다.

**수정 둘**
- `speed.yellow_decide_max_m: 60.0` (0 = 이전 동작) — 딜레마 구간 밖은 래치하지
  않는다. `red_lookahead_m` 와 같은 눈금이다.
- `speed.tl_hazard_far_blocker_enable` — 장애물이 정지선보다 `queue_head_max_m`(25)
  이상 앞이면 `traffic_light_hazard` 를 정지 원인으로 보지 않는다. 기준은
  대기열 판정(`_head_near_stopline`)과 **같은 상수**다.

**검증** (replay, 정지 구간):

| | 목표 > 0 인 틱 | never_stall | 상태 |
|---|---:|---|---|
| 11 off | **0 / 545 (0 %)** | ARMING 에서 멈춤 | SHIFT_HOLD 398 |
| **11 on** | **353 / 545 (64.8 %)** | **NEVER_STALL 146틱** | BREAKOUT 256 · CREEP_FAIL 196 |
| 18 off | 11 / 517 (2.1 %) | 없음 | SHIFT_HOLD 517 |
| **18 on** | **343 / 517 (66.3 %)** | **NEVER_STALL 115틱** | BREAKOUT 225 · CREEP_FAIL 197 |

`_obstacle_cause` 가 정지 구간 전 틱에서 참이 됐다 (11: 1167 False → True,
18: 1528 → True). **폐루프 확인은 배치가 필요하다** (사용자가 시뮬을 멈춰 미실시).

**"활성 span 중 새 시프트 생성 불가" 는 확인했으나 고치지 않았다** — 탈출구가
열리면 BREAKOUT·크립이 빠져나가므로 우선순위가 낮고, 재시프트는 span 회계
전반을 건드려 위험이 크다. 판단 필요 항목으로 남긴다.

### 회귀

- **replay 대표 10건 off 결정 10/10 동일** (`tests/replay_quick.txt` 신설).
- **pytest 1584 passed / 8 skipped / 0 failed.**

---

## [1] 정정 — 회전 차로 **제약은 켜지 못했다**, bias 60 으로 복귀

커밋 `69449ba` 에서 `turn_lane_constraint_enable: true` 로 켰는데, 그때 (c) 검증이
**불완전했다**. 지시안 기준은 "빌드 실패·**rc≠0** 건수 0" 인데 나는 빌드 예외만
셌고 `report()` 의 rc 를 안 봤다. 전수로 다시 재면:

| 설정 | rc≠0 |
|---|---:|
| 제약 off · bias 0 | **1** (dp_06 — 기존 결함) |
| **제약 ON · bias 0** | **5** (기존 1 + **신규 4**) |
| 제약 off · bias 60 | **1** (신규 0) |

신규 4건은 전부 같은 이유다:

```
lane_change_right  window 13.5 m   <= [오류] 창이 20 m 미만
(실전주행_교통류_01 · 03 · 07 · 13 — 전부 road 146 의 (146,0,1) → (146,0,2))
```

제약이 고르는 `(146,0,2)` 는 테이퍼로 열리는 차로라 점선 창이 **13.5 m** 뿐인데,
**경로 검증기 자신의 기준**(`MIN_LC_WINDOW_M` 20 m)이 그것을 실행 불가로 본다.
화살표는 그 차로를 요구하는데 기하가 못 따라간다 — **지도의 모순**이지 탐색이
고를 문제가 아니다.

지시안의 "실패가 나면 bias 60 으로 복귀" 를 따랐다:
`turn_lane_constraint_enable: false`, `turn_lane_bias_m: 60.0`.

**제약 코드는 남긴다** — 판정 자체는 옳고(위반 19 → 3), 창 기준이 완화되거나
그 자리 지도가 고쳐지면 그대로 켤 수 있다. 테스트 6건이 계약을 지킨다.

### 같은 커밋에서 저지른 실수 하나 더

`69449ba` 에 **`avoid_map.lane_map_avoid_enable: true` 가 딸려 들어갔다.**
배치용으로 켜 둔 것을 `git add -A config` 가 쓸어담았다. 커밋 D 판정은
"켜지 말 것" 이었다. 지금은 false 로 되돌렸고, 그 탓에 처음 잰 off 지문이
5/10 로 나왔다 (기준선이 lane_map on 이었다). 기준선을 바로잡으니 **10/10 동일**.

### `test_tight_turn` 3건 — 내 변경이 아니다

저장소 루트의 `waypoints.csv` 가 세션 중 **10점 → 3점**으로 바뀌었다. 그 파일은
사람이 자기 경로를 그릴 때 덮어쓰는 작업 파일인데 테스트가 그걸 직접 읽는다.
10점 원본은 커밋된 적이 없어 복구가 안 된다(이력의 10점본들은 `(2506,0,-1)` 을
만들지 않는다). 테스트가 **그 사례를 만들 때만** 검사하도록 고쳤다(아니면 skip).

**판단 필요**: 그 CSV 를 `tests/fixtures/` 로 옮겨 고정할지 — 원본을 주시면 한다.
