# 야간 작업 2026-09-09 → 09-10

> 아침 보고는 이 파일 맨 위(§0)에 채운다. 그 아래는 항목별 기록이다.

## §0 아침 보고

**최종 커밋**: `d539b4b` (그 위에 이 문서 갱신 커밋). **스위치는 전부 false** —
즉 커밋 상태의 주행 동작은 09-09 밤과 같다. 새 코드는 전부 꺼진 채 들어가 있다.

**배치**: quick 7건을 스위치 전부 on 으로 1회 돌렸다 (`logs/batch/20260910_004439`,
7/7 완료, 65분). 완주 3 / blocked 2 / no_progress 2 / 평균 감점 −13.3.
**그런데 이 결과로 on/off 를 판정할 수 없다** — 기준선(`20260909_093415`)이
그 뒤의 경로 재빌드 이전 것이라 **11·18 두 건의 경로가 다르다**.
경로가 같은 5건만 보면 감점이 **한 점도 안 달라졌다**(평균 −11.25 대 −11.25).

**기준선 대비**

| | 좋아진 것 | 안 바뀐 것 | 나빠진 것 |
|---|---|---|---|
| 경로 동일 5건 | 07 도달 +60.3 m (시프트가 **좌→우**로 옳게 바뀜) · 10 +11.1 m · 07 출발부 충돌 2→1 | 완주 2 대 2 · 감점 −11.25 대 −11.25 · 09 완전 동일 | 02 신규 충돌 1건 (회피 판단 없는 구간) · 07 종단 접촉 1.6 s → 250 s |
| 경로 다름 2건 | 11 477→3133 m(완주) · 18 2606→2876 m | — | 감점 11 −9→−18, 18 −9→−21 (더 갔으니 채점 기회도 늘었다) |

**VTD 상태**

| 시각 | 결과 |
|---|---|
| 09-09 23:57 | ping·22·9910·48179 **전부 응답** (직전 세션에선 전부 무응답이었다) |
| 09-10 00:43 | VTD PC 에 `실전주행_교통류` 세트가 **없어서** 21건 rsync 복사 (직전 배치 중단의 진짜 원인) |
| 09-10 00:44~01:49 | quick 7건 정상 완주 (65분) |
| **09-10 09:07** | **ping 100 % 손실 · 9910·48179·ssh 22 전부 무응답 → VTD 재시작 필요** |

같은 경로 기준선을 만들려고 09:07 에 스위치 전부 false 로 quick 을 다시 걸었으나
VTD 가 죽어 시작조차 못 했다. ssh 가 안 되어 원격 재시작도 불가.

**아침에 손댈 것 (한 줄)**: VTD 를 올리고 **커밋 상태(스위치 전부 false)로 quick
한 번** — 그것이 같은 경로 기준선이자 최종 커밋의 검증이고, 그 뒤에야 on/off 를
가를 수 있다.

**판단 필요**
1. **07 종단 250 s 접촉** — `never_stall` 1·2단계가 `stop_gap` 게이트를 풀어
   (`creep_ns_relax {'stop_gap': 851}`) 정지 차량에 0.87 m 까지 밀고 들어간다.
   이번 야간 스위치와 무관한 **기존 동작**이고, 기준선은 그 지점에 도달조차
   못 해 안 드러났다. 크립 바닥에 "접촉 금지" 하한이 필요하다.
2. **10_좌회전14** — 교차로 안에서 `reject: junction` + `cause_why: cross_guard`
   (538틱)로 시프트·크립이 동시에 닫힌다. 가드가 섰는데 앞도 막힌 경우의 처리.
3. **11·18 감점 증가**가 순수한 거리 효과인지 확인 — 같은 경로 기준선이 필요하다.
4. `18` 에 새로 붙은 **항목 13 (차로 변경 방향지시등) 1건**.
5. `turn_lane_constraint_enable` (09-09 이월) — `MIN_LC_WINDOW_M` 완화 없이는 못 켠다.

**14건 배치**: 안 돌렸다 (VTD 사망).

## VTD 상태

| 시각 | 확인 | 결과 |
|---|---|---|
| 09-09 23:57 | ping / 22 / 9910 / 48179 | **전부 응답** (직전 세션에서는 전부 무응답이었다) |

---

## [1] 시프트 중 얼어붙음 — **적신호 억제가 원인이 아니다**

지시안의 전제("SHIFT_HOLD + red_ahead 가 종방향을 잘랐다")는 로그가 반증한다.

`run_20260909_231730` (같은 시나리오의 긴 판, 189 s) rs 485.3 구간:

| t | 신호 | state | v_target | t_off |
|---:|---|---|---:|---:|
| 74–87 | **Red** | SHIFT_HOLD | 0.00 | +2.00 |
| 88–100 | **Green** | SHIFT_ACTIVE | **0.00** | +2.00 |
| 101–113 | Red | SHIFT_HOLD | 0.00 | +2.00 |
| 114–126 | **Green** | SHIFT_ACTIVE | **0.00** | +2.00 |
| … | (3 주기 더 반복) | | 0.00 | +2.00 |

**녹색 구간에도 v_target 0 이다.** 189 s 동안 rs 485.3 에서 한 번도 안 움직였다.
SHIFT_HOLD 는 적색 구간에만 뜨고, 정지는 신호와 무관하게 계속된다.

### (a) red_ahead 의 거리 조건 — **없다. 그것이 설계다**

[team_code/kr_rules.py:890](team_code/kr_rules.py#L890) `_red_ahead` 는
거리 조건이 아예 없다. 함수 독스트링이 명시한다:
"30 m 억제창(stopline_suppress_m)과 달리 **거리 조건이 없다**: 적신호면
100 m 밖에서도 회피하지 않는다." 근거는 2026-08-30 실측(대기열을 비켜 신호
위반이 될 뻔한 건)이다. SHIFT_HOLD 진입은
[kr_rules.py:2807](team_code/kr_rules.py#L2807) 의
`ot_span is not None and _red_ahead(planner) is not None` 뿐이라 **d_red 임계가
존재하지 않는다.** 거리 상한이 있는 변종 `_red_zone_d`(line 1028)는 있지만
SHIFT_HOLD 는 그 함수를 **쓰지 않는다**(주석에 명시).

→ 93 m 앞 정지선에 억제가 걸리는 것은 의도가 맞다. 그리고 **이 정지의 원인이
아니다.**

### 진짜 원인 — standoff 20.5 m 에서 크립이 매 틱 막힌다

v_target 0 을 만든 후보는 로그상 `route_end` 지만, 그 키에는 **standoff
프로파일이 합쳐져 있다** ([kr_rules.py:5489](team_code/kr_rules.py#L5489) —
`so < candidate` 로 같은 변수에 병합되고 로그 키는 `route_end` 하나다).
같은 틱 진단이 그 값을 그대로 보여준다:

```
standoff_d 20.5   standoff_id 2   standoff_v 0.0
creep_d 20.5      creep_standoff 22.0   creep_stop_m 7.0
so_creep false    creep_block "cause"        ← 189 s 내내 동일
```

`creep_block: 'cause'` 는 `_obstacle_cause` 가 거짓이라는 뜻이고, 거짓인 이유는
[kr_rules.py:2033](team_code/kr_rules.py#L2033):

```python
end_m = self.active_m if end_m is None else end_m       # active_m = 150
if self.last_d_end is not None and self.last_d_end <= end_m:
    return False                                        # route_end 유령차 사정권
```

이 주행의 `d_end` 는 **138.1 m** 다 (경로 `data/route.pkl` 총 578.6 m). 150 안이라
매 틱 거짓 → 크립이 영영 안 열린다.

**이 배제 폭이 틀렸다는 것은 이미 저장소가 알고 있다.** 같은 함수의 never_stall
경로는 2026-09-08 에 이미 좁혔고([kr_rules.py:2283](team_code/kr_rules.py#L2283)
주석), 그 근거가 그대로 여기에도 적용된다:

> `active_m` 은 유령차 **후보를 만드는 창**이지 "종점 때문에 서 있다" 는 뜻이
> 아니다 — 150 m 앞에서 선 것은 종점이 세운 게 아니다.

never_stall 만 `ns_end_m`(= `route_end.unlatch_m` 30) 으로 고쳤고, **크립
게이트는 150 을 그대로 쓰고 있었다.**

### (b) HOLD 탈출 조건 / never_stall 이 왜 안 떴나

탈출 조건은 두 개뿐이다 — `_red_ahead` 가 None 이 되거나(녹색),
`route_index > ot_span[1]`(span 통과). 앞차가 안 움직이면 **녹색이 와도
standoff 가 계속 0 을 준다** (위 표가 그것이다).

never_stall 은 `_obstacle_cause` 를 **좁은 창(30 m)** 으로 부르므로 종점 배제를
통과한다. 실제로 무장을 시도한다 — 로그에 `never_stall {state: ARMING}` 이 있다.
안 뜬 이유는 다른 것이다:

- `_ns_cause` 도 적신호를 배제한다 → **녹색 구간에만 시계가 돈다.**
- 무장 임계는 `never_stall.deadlock_max_s` = **20 s 연속**이다
  ([kr_rules.py:2388](team_code/kr_rules.py#L2388) `ns_ticks < ns_max_ticks`).
- 이 교차로의 녹색은 약 13 s 다. 실측 **최대 ns_s = 6.0 s** (456 ARMING 틱 전부
  단계 0). 황색으로 넘어가면 시계가 0 으로 리셋된다.

→ 신호가 주기적으로 도는 한 never_stall 은 **구조적으로 무장할 수 없다.**
`_obstacle_cause` 가 red_ahead 를 신호 계열로 배제한다는 지시안의 추측은
맞지만, 결정적인 것은 그 위의 **종점 배제(150 m)** 다.

### (c) 램프 중간에 얼면 차로선 위 — 사실이다

`t_off` 가 189 s 내내 **+2.00** 이다 (차로폭 3.2 m 기준 램프 약 62 %).
차체가 차로선 위에 걸친 채 정지 — 채점 항목 3 위반이다.
**이것은 (b) 와 같은 문제다**: 램프는 종방향 진행으로만 완성된다. 세워 놓고
횡만 진행시킬 수는 없다(급조향 금지). 크립이 열려 앞으로 나가면 램프가 자연히
끝난다 — 그래서 수정은 하나다.

### (d) 전수 — 같은 지문(SHIFT_HOLD + v_target 0 + 10 s 이상)

| 로그 | 건수 | 지속 |
|---|---:|---|
| run_20260903_100310 | 3 | 15.2 / 21.0 / 10.1 s |
| run_20260903_100458 | 2 | 21.0 / 17.7 s |
| run_20260903_104648 · 104807 | 1 + 1 | 14.4 / 10.4 s |
| 실전주행_교통류_01_좌회전24 | 1 | 15.9 s |
| 정적회피집중_02_우회전5 (×2 판) | 2 | 16.0 / 16.1 s |
| 정적회피집중_01_좌회전2 (×2 판) | 2 | 16.2 / 15.0 s |
| 정적회피집중_02_직진3 · 추월집중_05 | 2 | 20.8 / 20.9 s |
| 실전주행_교통류_07_연속교차로8 | 3 | 20.9 / 21.0 / 21.0 s |
| 실전주행_교통류_11_직진10 | 1 | 20.6 s |
| 실전주행_교통류_18_연속교차로14 | 1 | **31.6 s** |
| **run_20260909_231730 rs 485.3** | **5** | 12.9·13.0·13.0·13.0·11.0 s |

**대부분은 15~21 s 로 적색 1 주기다 — 녹색에 풀린다(정상).** 병적인 것은
231730 하나로, 같은 rs 에서 5 주기를 반복하며 **총 115 s** 를 못 움직였다.
그 판은 신호 주기가 아니라 위의 크립 잠금이다.

### 고침 — 크립 게이트의 종점 배제 폭을 never_stall 과 같은 축으로

`overtake.standoff_creep_end_narrow_enable` (기본 **false** = 이전 동작 150 m).
켜지면 `_standoff_creep` 의 `_obstacle_cause` 호출이 `end_m=ns_end_m`(30) 을
쓴다 — **never_stall 이 이미 쓰는 값과 같은 상수**다(두 벌을 만들지 않는다).
종점 정지 자체는 그대로 지킨다: 30 m 안에서는 켜져도 막힌다.

`tests/test_creep_end_narrow.py` 5건 — off 는 138.1 m 에서 막히고, on 은 열리며,
12.0 m(진짜 종점)에서는 on 도 막힌다. 신호 축은 on/off 동일.

**적신호 억제(red_ahead)는 건드리지 않았다.** 분석 결과 원인이 아니었고,
2026-08-30 실측 근거가 있는 규칙이다.

---

## [2] 정지 차량을 신호 대기 줄로 오판 — 지시안의 (a)(c) 는 성립하지 않는다

로그 `run_20260909_230925` (40.4 s, road 128 sec 6, rs 32.5 에서 27 s 무진전).

### (a) 게이트가 좌측을 검사한 것이 아니다 — **두 칸 게이트는 정상 동작한다**

`reject` 는 `left:zone_no_through_lane` 이지만, 같은 틱의 **`rejects` 전수**가
답이다:

```
"rejects": ["right:occupied_mid@p1", "left:zone_no_through_lane@p1"]
"lane_plan": {"pick": "[128,6,-5]", "side": "right", "hops": 2, "armed": true}
```

**우측이 먼저 평가됐다.** `_side_pass` 의 `_order` 가 `lane_plan.side` 를 보고
순서를 바꾸는 것(2bdeeef)은 그대로 걸려 있다. `reject` 필드가 **마지막 side 의
라벨만** 남기는 것이 오해의 원인이다 (코드 주석에 명시된 성질이고, 그래서
`rejects` 리스트가 따로 있다).

그리고 우측 기각 사유 `occupied_mid` 는 **옳다** — 같은 틱 차로 지도가
중간 차로가 막혔다고 말한다:

```
free_run  (128,6,-3) 20.5  (128,6,-2) 21.0  (128,6,-4) 20.1  (128,6,-5) 80.0
blocked_by  (128,6,-4)→4   (128,6,-3)→3   (128,6,-2)→2
```

정지 차량 3 대가 **나란히** 서 있다. 두 칸 오른쪽(-5)은 비어 있지만 거기 가려면
중간 차로(-4)를 지나야 하고 그 차로는 20.1 m 앞이 막혀 있다. 램프(15.5 m) +
여유가 들어갈 자리가 없다. **시프트를 안 한 것이 맞다.**

→ 고칠 것은 로직이 아니라 **보고**다. `reject` 한 줄만 보면 반대쪽을 검사한
것처럼 읽힌다. `rejects` 를 먼저 보도록 이 문서에 남긴다.

### (b) 큐 억제는 **적색 구간에만** 걸렸다 — 녹색에는 이미 풀린다

| t | 신호 | 상태 | queue |
|---:|---|---|---|
| 1–12.9 | Red | SUPPRESS/queue | 유지 |
| **12.9–24.7** | **Green (5=녹색+좌)** | PREEMPT → REACTIVE | **`queue_reject: green_expired`** |
| 24.7–27.5 | Yellow | SUPPRESS/queue | 유지 |
| 28.6–40 | **Red** | SUPPRESS/queue | 유지 |

지시안의 "신호는 [23,5]인데 큐로 본다" 는 성립하지 않는다 — 녹색 구간에서는
`green_expired` 로 이미 해제돼 있었고, 그 구간의 정지 사유는 위 (a) 의
`occupied_mid` 다. 큐가 유지된 구간은 **전부 적색·황색**이다.

### (c) 요청한 `queue_stale_release_enable` 은 **이미 구현돼 있다**

`_is_queue_v2` [kr_rules.py:1955](team_code/kr_rules.py#L1955):

```python
if signaled:
    if self.green_since_ticks >= self.q_green_release_ticks:   # q_green_release_s = 3.0
        self.q_reject = 'green_expired'
        return False
```

"머리 차량이 안 움직이고(= blockers 에 남아 있고) 신호가 적색이 아니면 해제" 가
정확히 이 세 줄이다 (선두가 떠나면 blockers 에서 빠져 그 틱에 저절로 풀린다).
같은 일을 하는 스위치를 하나 더 두면 **상수·판정이 두 벌**이 된다 —
CLAUDE.md 의 "상수는 한 곳에서만" 에 어긋나므로 **만들지 않았다.**

적색 중에 안 움직이는 앞차를 비켜 가는 것은 신호 위반이라 이 축에서는 열 수 없다.
적색 중 무한 정지의 탈출구는 큐 해제가 아니라 **크립**이고, 그것이 [1] 이다.

### (d) 큐 뒤 정지 거리 — 고쳤다 (`queue_close_gap_enable`, 기본 off)

`standoff`(기본 `standoff_floor_m` 22 m)는 **시프트 전이가 들어갈 공간**이다.
큐 뒤에서는 비켜갈 것이 아니라 줄을 서므로 그 공간이 필요 없다. 실측:

| 로그 | rs | standoff_d |
|---|---:|---:|
| 실전주행_교통류_18_연속교차로14 | 78.4 | 20.6 m |
| run_20260909_232350 | 485 | 20.5 m |

켜면 `_standoff_profile` 의 기준선이 `queue_stop_gap_m`(5.0) 으로 바뀐다.
큐 판정은 새로 만들지 않고 이번 틱 `_tick_queue` 를 그대로 쓴다 — `lane_map` 의
큐 제외와 **같은 축**이라야 억제 기준이 두 벌이 되지 않는다.
`tests/test_queue_close_gap.py` 5건.

### 덤 — `creep_block: 'cause'` 에 세부 사유를 붙였다

두 로그 모두 `creep_block: 'cause'` 였는데 그 한 단어로는 신호인지 종점인지
큐인지 알 수 없었다. `_obstacle_cause` 가 어느 배제에 걸렸는지
`cause_why`(rtor / tl_hazard / walker / stop_sign / end_latch / sl_hold /
yellow / cross_guard / **route_end** / red_ahead / signal_zone / **queue** /
no_blocker) 로 남긴다. **판단에는 관여하지 않는 순수 진단**이다.

---

## [3] 차로 지도가 시프트를 소유한다 (`lane_map_owns_shift_enable`, 기본 off)

켜지면 "어디로·언제" 는 `lane_plan` 만 정하고, 옛 `_try_overtake` 는 안전
검사(게이트 10개)와 안전망(REACTIVE·BREAKOUT·never_stall)만 남는다.

| 구현 | 내용 |
|---|---|
| side 후보 | `_order = (lane_plan.side,)` — **계획한 쪽 하나**. 게이트에서 떨어지면 반대쪽으로 새지 않고 그 틱은 포기한다 (지도가 매 틱 다시 고르므로 다음 틱에 다시 온다) |
| 시점 | `lane_plan.armed`(램프 시작점 통과)면 관찰·시간예산과 무관하게 즉시 시프트 |
| 트리거 | `lane_map_decide_m` **50 → 80** (`lane_map_ahead_m` 와 동일) |
| 갱신 | `lane_switch_margin_m`(20) — 새 목표의 free_run 이 지금 목표보다 이만큼 길 때만 재타겟 |
| 동률 | ① 다음 교차로 유효 차로 쪽 (`valid_entry_lanes` — 새 재료 안 만든다) ② **오른쪽**(우측통행) |

`_chain`·`ot_span` 을 읽는 9개 함수·`shift_route_around_actors`·게이트 10개는
손대지 않았다.

### 지시안과 다르게 한 것 하나 — 2바퀴 루프는 **그대로 둔다**

지시안은 `solid_second_pass` 를 건너뛰라고 했다. 그렇게 만들어 돌려 보니
`avoid_sim` 11 케이스가 **나빠졌다**:

| 케이스 | 지도만 on | owns + p2 생략 | owns + **p2 유지** |
|---|---:|---:|---:|
| 7 실선 구간 | 0.0 s | **23.2 s** | 0.0 s |
| 8 다음 좌회전 | 0.0 s | **23.2 s** | 0.0 s |
| 9 양쪽 다 막힘 | 25.9 s | 24.1 s | **0.0 s** (차로 [-4,-3,-2]) |
| 11 두 칸 + 중간 점유 | 5.5 s ([-3,-2,-1]) | **21.2 s** ([-1]) | 5.5 s ([-3,-2,-1]) |

건너뛰면 정지가 늘고 두 칸 도달을 잃는다. 그대로 두면 **케이스 9 가
25.9 → 0.0 s** 로 오히려 좋아진다. 실선 완화의 옳고 그름은
`solid_second_pass_enable` 소관이지 이 스위치가 정할 일이 아니다.

### `avoid_sim` 11 케이스 on/off 대조 (owns_shift + retarget on)

| # | 케이스 | off 정지 | on 정지 | on 차로 | 기대 충족 |
|---:|---|---:|---:|---|---|
| 1 | 단독 장애물 | 0.0 | 0.0 | [-2,-1] | ✔ |
| 2 | 1·2차로 나란히, 3차로 빔 | **25.1** | **0.0** | [-3,-2,-1] | ✔ 두 칸 |
| 3 | 엇갈림 | 0.0 | 0.0 | [-3,-2,-1] | ✔ |
| 4 | 걸쳐 선 차 | **23.1** | **0.0** | [-3,-2,-1] | ✔ |
| 5 | 연속 3대 | 9.0 | 9.0 | [-3,-2,-1] | ✔ 복귀 없음 |
| 6 | 신호 대기 줄 | 39.5 | 39.1 | [-1] | ✔ **추월 안 함** |
| 7 | 실선 구간 | 0.0 | 0.0 | [-2,-1] | (기존과 동일) |
| 8 | 다음 좌회전 | 0.0 | 0.0 | [-2,-1] | ✔ |
| 9 | 양쪽 다 막힘 | **25.1** | **0.0** | [-4,-3,-2] | ✔ |
| 10 | 먼 차로에만 장애물 | 0.0 | 0.0 | [-1] | ✔ 무반응 |
| 11 | 두 칸 + 중간 점유 | 4.6 | 5.5 | [-3,-2,-1] | ✔ 3차로 도달 |

충돌 0 / 조향 포화 0 은 전 케이스 on·off 모두. 큐(6)·무반응(10)은 안 바뀐다.
`tests/test_owns_shift.py` 7건.

---

## [4] quick 배치 — 스위치 전부 on

**VTD 복구 경위**: 직전 세션에서 배치가 "시나리오 파일 없음" 으로 중단됐는데,
원인은 경로 불일치가 아니라 **VTD PC 에 `실전주행_교통류` 세트가 아예 없었던
것**이다 (`/home/mjw/scenarios` 에 `정적회피집중` 만 있었다). 09-10 00:43 에
21개 시나리오(8.4 MB)를 rsync 로 복사하고 배치를 시작했다.

배치 스위치 (커밋 상태는 전부 false — 배치용 임시 on):

| 키 | 값 |
|---|---|
| `avoid_map.lane_map_avoid_enable` | true |
| `avoid_map.lane_map_no_return_enable` | true |
| `avoid_map.lane_map_retarget_enable` | true |
| `avoid_map.lane_map_owns_shift_enable` | true |
| `avoid_map.lane_map_span_sections_enable` | true (커밋 기본값) |
| `avoid_map.lane_map_decide_m` | 80.0 (커밋 기본값) |
| `avoid_map.lane_switch_margin_m` | 20.0 (커밋 기본값) |
| `overtake.standoff_creep_end_narrow_enable` | true |
| `overtake.queue_close_gap_enable` | true |

### 기준선 — `logs/batch/20260909_093415` (차로 지도 off)

```
7건 · 완주 2 / blocked 4 / no-data 1 · 평균 감점 -10.5 · 최악 07_연속교차로8 (-21)
  07_연속교차로8   blocked  2821.9 m  9:37  17.6 km/h  -21
  11_직진10        blocked   477.2 m  1:04  26.9 km/h   -9
  18_연속교차로14  blocked  2606.2 m  8:23  18.7 km/h   -9
  10_좌회전14      blocked   256.8 m  1:22  11.2 km/h   -3
  01_PathShape03   no-data (20 s 로그 정체)
  02_venue0903     완주      751.0 m  2:37  17.2 km/h  -12
  09_우회전13      완주     3002.6 m  7:17  24.7 km/h   -9
정지선: 침범(slf>0) 9건 · slf 평균 -0.41 · 최대 +3.28
```

[5] 판정 기준: **완주 수 ≥ 2 AND 총점 평균 ≥ -10.5 AND 새 충돌 0**.

### 진행 기록 (시나리오별)

**1/7 실경로_01_PathShape03 — 완주, 총점 91 (감점 −9)**
기준선은 `no-data (20 s 로그 정체)` 였으므로 형식상 개선이지만 **이번 변경의
공로가 아니다**: 이 시나리오는 회피 활동이 0 이다 (시프트 0, `lane_plan.pick`
0틱, `상태 {}`). 기준선 쪽 수집 실패가 이번엔 안 났을 뿐이다.
차로 유지 2건 −6, 적색신호 정지 2건 −3.
(차로 지도는 정상 동작 확인 — `span_alias: 2` 로 섹션 승계가 실제 지도에서 걸렸다.)

**2/7 실경로_02_venue0903 — 미완주 rs 496.4/793.1, 총점 88 (감점 −12)**
기준선은 완주(751.0 m) 였다. **그러나 코드 회귀가 아니라 교통류 차이다.**

| | 기준선 09-09 09:34 | 오늘 09-10 00:46 |
|---|---|---|
| rs 493 의 objects | **[] (한 대도 없음)** | 정지 차량 4 대 |
| 480~520 m 통과 | 11.3 s | **130 s 이상 무진전** |

막은 것은 id 2 — **8.33 m/s 로 달리다 선 교통류 차량**이고, 자차 차로는
`(190, 0, 1)` **1차로 단독 도로**다. 그래서:

```
rejects: ["left:no_neighbor@p1", "right:no_neighbor@p1"]
lane_plan: {"cands": {}, "pick": null, "why": "no_candidate"}
lane_map:  hops {"[190,0,1]": 0}      ← 이웃 차로가 아예 없다
```

`pick` 이 null 이므로 **owns_shift 는 이 틱에 소유권을 갖지 않는다**
(`_owns_shift` 는 pick 을 요구한다). 옛 로직이 그대로 돌았고 양쪽 다 이웃이
없어 기각했다 — 옳은 판단이다. 비켜갈 유일한 길은 중앙선 침범(항목 4)이다.

부수 관찰: id 9·14·23·24 도 최종 속도 0 이다 — **교통류 자체가 앞에서 정체**했다.
`never_stall` 은 ARMING 만 반복하고 단계 0 에 머문다 (같은 20 s 연속 요건).

**판정에 미치는 영향**: quick 7건은 교통류가 매 판 달라 완주 수 비교에 잡음이
있다. [5] 판정에서 이 건은 "교통류 차이" 로 분리해 기록한다.

**3/7 실전주행_교통류_07_연속교차로8 — 미완주 rs 2882.6/3135.0, 총점 79 (감점 −21)**
**이번 작업의 핵심 확인 지점이고, 의도한 대로 나왔다.**

| | 기준선 09-09 09:34 | 오늘 |
|---|---|---|
| 시프트 | rs 2714.1 **left** (콘 테이퍼 **안쪽**) | rs 2766.2 **right**, 1 hop |
| 도달 거리 | blocked **2821.9 m** | **2882.6 m** (+60.7) |
| 재타겟 | — | 0회 (필요 없었다 — 처음부터 옳은 쪽) |
| 조향 포화 | — | **0** |
| `cause_why` | — | **없음** (크립이 배제로 막힌 틱 0) |

지난 세션 분석의 결론은 "rs 2714.1 결정 시점에 지도가 비어 있어 옛 로직이
무정보로 왼쪽을 골랐다" 였다. 섹션 승계 수정으로 그 지점의 지도가 채워지고,
`decide_m` 80 과 동률 규칙(우측)으로 **오른쪽**이 선택됐다. rs 2822 정지는
풀렸다 (2882.6 까지 진행).

감점은 −21 로 기준선과 같지만 **거리가 60 m 늘었다**. 항목: 제한속도 1,
보호구역 1, 차로 유지 4, 적색신호 8, 장애물 2.

**4/7 실전주행_교통류_18_연속교차로14 — 미완주 rs 2876.5/3063.5, 총점 79 (감점 −21)**

| | 기준선 | 오늘 |
|---|---|---|
| 도달 거리 | blocked **2606.2 m** | **2876.5 m** (+270.3) |
| rs 2560.3 | **blocked** | 구간 2540~2620 을 **15 s 에 통과** (최저 v 2.02, 무정지) |
| SHIFT_HOLD ≥10 s | **1건 31.6 s** | **0건** |
| 시프트 | — | rs 2511.3 left 1 hop |
| 조향 포화 / `cause_why` | — | 0 / 없음 |
| 감점 | **−9** | **−21** |

**감점 비교의 함정을 여기에 적어 둔다.** 기준선이 −9 인 것은 잘한 것이 아니라
**2606 m 에서 멈춰 더 채점될 기회가 없었기** 때문이다. 270 m 를 더 달리면
신호·차로 판정을 그만큼 더 받는다. 그래서 "총점 평균" 하나로 on/off 를 가르면
**덜 간 쪽이 이긴다** — [5] 판정에서 이 점을 반드시 같이 본다.

새로 붙은 항목: 13 차로 변경 방향지시등 1건 −3 (기준선엔 없다). 확인 필요.

**5/7 실전주행_교통류_10_좌회전14 — 미완주 rs 267.9/3147.4, 총점 97 (감점 −3)**
기준선 blocked 256.8 m · −3 → 오늘 267.9 m · −3. 거의 같다 (+11 m).

**새로 넣은 `cause_why` 진단이 바로 답을 줬다.** 예전엔 `creep_block: 'cause'`
한 단어였는데, 이제 원인이 찍힌다:

```
state REACTIVE  blocker 29 (13.5 m, 정지)  reject "junction"  j_release true
creep_block "cause"   cause_why "cross_guard"   ← 538틱
```

자차가 **교차로 안**이라 시프트는 `junction` 게이트가 막고(옳다), 크립은
**통과 가드(`cross_guard`) 래치**가 막고 있다. 두 축이 동시에 닫혀 있어
13.5 m 앞 정지 차량 뒤에서 못 움직인다.

`cross_guard` 는 "교차로를 이미 통과 중이니 멈추지 말 것" 축이라 크립 배제
목록에 있는 것 자체는 맞지만, **가드가 서 있는데 앞도 막힌 경우**는 그 전제가
깨진다. → **판단 필요** 항목으로 남긴다 (이번 야간 범위 밖).

**6/7 실전주행_교통류_09_우회전13 — 완주 3005.0 m, 총점 91 (감점 −9)**
기준선도 완주 3002.6 m · −9 였다. **완전히 같다** — 이미 되던 것이 안 깨졌다.
시프트 2회(rs 1527.6·2389.3, 둘 다 left, `lane_plan` 미소유 = 옛 로직),
재타겟 0, 조향 포화 0, `cause_why` tl_hazard 1틱뿐.

**7/7 실전주행_교통류_11_직진10 — 완주 3133.2 m, 총점 82 (감점 −18)**
기준선 blocked 477.2 m. 겉으로는 최대 개선이지만 **판정 근거가 못 된다** — 아래 참조.

---

## [5] 판정 — **결론: 스위치는 전부 false 유지. 기준선이 무효라 판정 불가.**

### 배치 원표 (logs/batch/20260910_004439)

```
7건 · 완주 3 / blocked 2 / no_progress 2 · 평균 감점 -13.3
```

| # | 시나리오 | 도달 | 기준선 도달 | 감점 | 기준선 감점 | 경로 |
|---|---|---:|---:|---:|---:|---|
| 1 | 01_PathShape03 | 완주 870.9 | no-data | −9 | — | 동일 |
| 2 | 02_venue0903 | 496.4 | 완주 751.0 | −12 | −12 | 동일 |
| 3 | 07_연속교차로8 | 2882.2 | 2821.9 | −21 | −21 | 동일 |
| 4 | 18_연속교차로14 | 2876.0 | 2606.2 | −21 | −9 | **다름** |
| 5 | 10_좌회전14 | 267.9 | 256.8 | −3 | −3 | 동일 |
| 6 | 09_우회전13 | 완주 3005.0 | 완주 3002.6 | −9 | −9 | 동일 |
| 7 | 11_직진10 | 완주 3133.2 | 477.2 | −18 | −9 | **다름** |

### 기준선이 무효인 이유 — 경로가 그 사이에 바뀌었다

기준선 `20260909_093415` 는 09-09 **09:34** 실행이고, 그날 낮에 커밋된
`taper_penalty_enable` + `turn_lane_bias_m: 60` 이 **46 경로를 다시 지었다**.
route.pkl 차로열을 직접 대조했다:

| 시나리오 | 기준선 m | 오늘 m | 차로열 |
|---|---:|---:|---|
| 01 · 02 · 07 · 09 · 10 | — | — | **동일** |
| **11_직진10** | 3149.6 | 3141.9 | **69개 전부 다름** (idx 0 부터) |
| **18_연속교차로14** | 3068.4 | 3063.5 | idx 37 부터 16개 다름 |

**11 의 개선은 회피가 아니라 경로다.** 지시하신 (a)(b)(c) 확인 결과:

- **(a)** 장애물은 **있었다**. id 4·5·6·7·8·9 전부 `obstacle`, 속도 0.00,
  rs 400~499 — **기준선과 같은 자리 같은 개수**다. blocker 7 도 rs 418~499 에
  그대로 있다. "장애물이 없었다" 는 아니다.
- **(b)** 그런데도 **판정 근거가 못 된다.** 자차가 **다른 차로에 있었다**:

  | | rs 300.5 | rs 368 | rs 412 | 시프트 |
  |---|---|---|---|---|
  | 기준선 | `(126,0,4)` | `(2423,0,-2)` | `(2423,1,-2)` | rs 389.8 **left** |
  | 오늘 | `(126,0,3)` | `(2423,0,**-1**)` | `(2423,1,-1)` | **없음** |

  차로 지도가 본 것: `free_run` 이 `-1` 은 80.0, `-2`·`-3` 은 43.4→11.4 로 막힘.
  **콘은 −2·−3 차로를 막고 −1 은 비어 있다.** 오늘은 경로가 처음부터 −1 로
  갔으므로 회피할 일이 없었다 (`t_off` 전 구간 +0.00 = 계획 경로 그대로).
  → **11 은 회피 개선의 증거가 아니다. 경로 재빌드의 결과다.**
- **(c)** 그래서 판정을 "특정 rs 에서 시프트 생성" 으로 하지 않는다. 아래는
  **경로가 동일한 5건**만으로 다시 계산한 통계다.

### 경로 동일 5건만의 통계 — **차이가 없다**

| | 기준선 | 오늘 |
|---|---:|---:|
| 완주 수 | 2 (02, 09) | 2 (01, 09) |
| 감점 (02/07/09/10) | −12 / −21 / −9 / −3 → 평균 **−11.25** | −12 / −21 / −9 / −3 → 평균 **−11.25** |
| 충돌 | 3 (전부 07) | 3 (02×1, 07×2) |
| 07 도달 | 2821.9 | **2882.2** (+60.3) |
| 10 도달 | 256.8 | **267.9** (+11.1) |

**네 시나리오의 감점이 한 점도 안 달라졌다.** 원표의 −10.5 → −13.3 악화는
전부 11(−18)·18(−21) 에서 왔고, 그 둘은 **경로가 다르다** — 더 멀리 갔기
때문에 채점 기회가 늘어난 것이지 운전이 나빠진 것이 아니다.

### 스위치별 실제 발동 — 셋은 한 번도 안 걸렸다

| 스위치 | 발동 틱 | 판정 |
|---|---:|---|
| `lane_map_span_sections_enable` | **54,417 / 60,568** (89.8 %) | 지도를 채운 주역 |
| `lane_map_owns_shift_enable` | 시프트 결정 **2건** (07, 18) | 표본 2 |
| `standoff_creep_end_narrow_enable` | **0** (`cause_why=route_end` 0틱) | **증거 없음** |
| `queue_close_gap_enable` | **0** (`creep_standoff=5` 0틱) | **증거 없음** |
| `lane_map_retarget_enable` | **0** (RETARGET 0틱) | **증거 없음** |
| 두 칸 시프트 | **0** | 이번 배치에 없었다 |

[1]·[2](d) 두 스위치는 **이 배치에서 아무 일도 하지 않았다** — 좋아지지도
나빠지지도 않았다. 그 둘이 겨냥한 상황(짧은 경로의 종점 150 m 창, 큐 뒤 정지)이
quick 7건에 없었다.

### 충돌 — 새로 난 1건은 어느 스위치와도 무관하다

경로 동일 5건 기준 충돌 수는 3 대 3 으로 같지만 구성이 다르다:

| | 기준선 | 오늘 |
|---|---|---|
| 07 출발부 (s 50~66) | 2건 | **1건** (줄었다) |
| 07 종단 | s 2817.7, **1.6 s** | s 2860.6, **250.2 s** |
| 02 s 374.1 | 없음 | **1건 (신규)** |

**02 신규 충돌**: 그 구간 `state=None`, `lane_plan=None` — **회피 판단이 아예
없었다**. 조향 −0.48 의 곡선 주행 중 마주 오는 차량 22(5.5 m/s)와 중심간
2.46 m 까지 붙었다. 차로 지도는 02 에서 **pick 0틱·시프트 0회**라 어떤 결정도
바꾸지 않았다. → 스위치 탓이 아니다.

**07 종단 250 s 접촉**: 이쪽이 진짜 문제다. `standoff_d` 가
**22.0 → 6.9 → 5.4 → 3.3 → 1.2 → 0.87** 로 **한 칸씩 밀고 들어간다.**
원인은 진단이 그대로 말해 준다:

```
creep_ns_relax {'stop_gap': 851}      ← never_stall 이 정지거리 게이트를 푼다
never_stall {ARMING 3523, LEVEL1 687, LEVEL2 338}
creep_open_why {'delay': 918, 'never_stall': 340, 'need': 80}
creep_standoff 22.0 (3786틱 전부)     ← queue_close_gap 은 안 걸렸다
```

`_standoff_creep` 의 A2 규약 "1단계는 ① stop_gap 을 건너뛴다" 가 그대로
동작한 것이다. **이번 야간 스위치가 아니라 기존 never_stall 동작**이고,
기준선은 2821.9 에서 멈춰 이 지점에 **도달조차 못 했다**.

### 판정

지시하신 세 기준을 원표로 보면 `완주 3≥2 ✅ / 평균 −13.3 < −10.5 ❌ /
새 충돌 ❌` 이다. 그래서 "어느 스위치 때문인지 특정" 을 했고, 결과는
**어느 스위치도 아니다** — 악화분은 전부 **경로 재빌드**에서 왔고,
신규 충돌은 회피 판단이 없는 구간에서 났다.

동시에 **좋아졌다고 말할 근거도 부족하다**: 경로 동일 5건의 감점은 완전히
같고, `owns_shift` 표본은 2건, 나머지 세 스위치는 0건이다.

→ **스위치는 전부 false 로 유지한다** (커밋 상태 그대로). "배치 없이 스위치를
켜지 않는다" 와 "아침에 남아 있는 커밋은 배치를 통과한 상태여야 한다" 를 둘 다
지키는 유일한 선택이다.

### 다시 돌려야 할 것 — 같은 경로 기준선

판정이 막힌 유일한 이유는 **기준선이 낡았다**는 것이다. 09-10 09:07 에
스위치 전부 false(=커밋 상태)로 quick 을 다시 걸어 **같은 경로 기준선**을
만들려 했으나 **VTD 가 죽어 있었다**:

```
09:07:05  ping 100 % 손실 · 9910 무응답 · 48179 무응답 · ssh 22 timeout
```

원격 재시작 절차도 ssh 가 안 되어 시도할 수 없었다. → **VTD 재시작 필요.**

---

# 09-10 오전 — 가설 검증과 수정 6건

## 가설 판정표 (지시안 (1)~(6))

| | 가설 | 판정 | 근거 |
|---|---|---|---|
| (1) | 큐 오판으로 free_run 80 | **틀림** | 230925 **녹좌 215틱**이 `green_expired` 해제 상태였고 free_run 도 실값. 큐 유지 틱은 전부 적(351)·황(58). 제안한 해제 규칙은 `_is_queue_v2` 에 이미 있다 |
| (2) | red_ahead 가 거리 무관 SUPPRESS | **틀림** | 그 반환은 `suppress_mode == 'legacy'` 안이고 기본은 `queue_only`. 거리 무관 적색 게이트는 SHIFT_HOLD 뿐이고 `ot_span` 활성일 때만 — **생성을 막지 않는다** |
| (3) | `_side_is_clear` 가 뒤를 보고 앞을 못 본다 | **맞음** ★ | `near = {t} ∪ succ ∪ **pred**`, 반경은 **자차 중심** 30 m. 로그 재판정 198/198·66/66 통과로 뒤집힘 |
| (4) | 단일 후보 기각 시 대안 없음 | **맞음** | owns_shift 가 `_order = (side,)` |
| (5) | span 해제 조건이 하나뿐 | **부분 틀림** | 해제 경로가 둘(`span_lost_restore` 기본 true). 재타겟도 **도달**한다 — 시프트 활성 2,647틱 중 **889틱**이 pick 을 가진 채 진입. RETARGET 0 은 `ot_target == pick` 때문 |
| (6) | red_hold 로 65 % 동결 | **틀림** | 231730 은 5 주기 189 s 동안 **녹색에도** v_target 0. 원인은 크립 게이트 |

## geom 자기잠금 — 원인은 크립이 아니라 **span 잠금**

기각 사유 분포는 `geom 7278 · no_neighbor 2644 · junction 582 · occupied 292` 로,
`occupied` 는 2.5 % 다. 그런데 geom 도 **원인이 아니라 증상**이다:

- s_rel ≥ 20 구간의 기각 사유는 **"기각 없음"** — 게이트가 아예 평가되지 않았다.
  그 구간 상태는 전부 `SHIFT_HOLD`/`SHIFT_ACTIVE`, 즉 **span 활성**이라
  `_try_overtake_inner` 가 조기 반환한다.
- 그 동안 `lane_plan.pick` 은 **248틱 전부 None**.
- 07 blocker 9 는 **78.3 m** 까지 기회가 있었는데 10.1 m 에서 기각.
  기각 3,803틱의 s_rel 중앙값은 **3.9 m** 다.

pick 이 None 인 이유는 트리거가 **자차가 물리적으로 선 차로**만 보기 때문이다.
밀린 경로 위에서는 그 차로가 (비켜 왔으니) 늘 비어 보인다:

```
rs 2802.4  물리 차로 (2076,3,4) free_run 80.0 → mine ≥ decide_m(80) → None
           복귀 차로 (2076,3,3) free_run  7.5 ← 콘이 전부 여기 있다
```

레인그래프 확인: 콘 5·6·7·9 는 **전부 (2076,3,3)** (s 138.7·156.7·174.7·210.7).
자차는 rs 2766.2 에 lane 3 → lane 4 로 우측 시프트했고, 그래서 콘 5·6·7 은 밀린
회랑 옆으로 빠지고 **복귀 전이가 다시 lane 3 으로 들어가는 지점의 콘 9** 만
회랑에 남았다. **지도와 회랑은 같은 콘 열을 다른 축으로 재고 있었을 뿐 둘 다 맞다.**

→ 트리거를 **둘 중 나쁜 쪽**으로 (`3940047`). 재판정: 시프트 활성 619틱에서
발동이 **99 → 619**, 첫 발동 rs **2779.5** (시프트 13 m 뒤, 콘 9 가 회랑에
잡히는 rs 2802.4 보다 **23 m 앞**).

### 채택하지 않은 것

- **(b) 크립 보존** — avoid_sim 12 케이스 off/on **전건 동일(효과 0)**. 구현했다
  뺐다. 사용자도 가설 철회.
- **(c) 속도 need** (`trans_m_by_speed_enable`, 커밋은 했으나 **켜지 말 것**) —
  저속을 막는 것은 횡가속이 아니라 **조향각**이다:
  `L ≥ π·√(Y/(2·κ_max))`, `κ_max = tan(max_steer)/wheelbase` = **9.4 m**.
  바닥을 4.0 으로 두고 돌렸더니 avoid_sim 11 에서 **조향 포화 0 → 27틱**.
  바로잡으면 need 15.0 → 12.4 뿐이고 재판정 통과율 **2 % / 0 % / 0 %**.
- **(e) no_neighbor** — 2,644틱 **전부** 지도 hops 에도 이웃이 없다(0건).
  소멸 차로·섹션 경계 불일치가 아니다.

## 11시 실주행에서 드러난 두 건

`run_20260910_110743` rs 500.1, 60 s 정지.

### 1. `3940047` 이 **발동조차 안 했다** — 내 버그

`ot_from_lane` 을 **차로 키**로 저장해, 자차가 섹션을 넘으면 `free_run` 키와
안 맞아 조용히 무효가 된다. 시프트는 rs 459.0 에 `(2756,**3**,5)` 에서 났고
정지 지점은 `(2756,**1**,4)` 라 조회가 전부 None 이었다. → **hop 오프셋**으로 변경.

### 2. 큐 제외가 트리거를 죽인다

큐 제외 대상은 `_tick_corridor`(= **내 차로** 회랑) id 라, 구조적으로
**트리거를 만드는 바로 그 객체**만 정확히 지운다.

```
회랑    blocker 2, s_rel 6.1
지도    free_run[(2756,1,4)] = 80.0, blocked_by 에 id 2 없음, queue_dropped 1
→ pick=None → 두 번째 시프트 없음 → PDM vehicle 후보가 v_target 0 으로 60 s
```

3점 투영 실패가 아니다 — 레인그래프는 셋 다 찾는다(id2 →(2756,0,4),
id3 →(2756,0,3), id4 →(2756,0,5), `span_alias 8` 로 자차 섹션에 접힘).
id 3·4 는 `blocked_by` 에 있고 id 2 만 없다.

**전수**: 그 두 로그에서 "회랑 blocker 있는데 지도 내 차로 80.0" 이
**741틱 (24.4 %)**, 그 **100 % 가 `queue_dropped>0` 이고 100 % 가 `pick=None`**.
(어젯밤 배치는 850틱 1.4 %, 큐 원인 1 % — 지도를 실제로 쓰기 시작하면서 이
사각이 지배적이 됐다.)

→ 빼지 말고 `queue_lanes` 로 **표시**만 (`lane_map_queue_mark_enable`).
그 틱의 실제 지도로 재계산: `mine = 6.1 < 80` **발동**, 후보 중
`(2756,1,3)` 9.9 < need 22.3 탈락 · `(2756,1,5)` 10.5 탈락 · `(2756,1,6)` 통행불가
→ **pick = `(2756,1,2)`** (좌 2칸).

## 다음 배치에서 볼 것

- `queue_lanes` 가 로그에 뜨는지
- rs 500 에서 `pick = [2756,1,2]` 가 나오는지
- 741틱 증상(회랑 blocker 있는데 지도 80.0)이 사라지는지
- `geom`(3,803) · `occupied`(292) 기각 수
- `RETARGET` 이 0 을 벗어나는지

**기준선 주의**: `20260909_093415` 는 11·18 의 **경로가 다르다**(그 뒤의 경로
재빌드). 판정하려면 **같은 경로로 스위치 off 판**을 한 번 더 돌려야 한다.

## pytest

전체 **1648 passed / 8 skipped / 0 failed** (16분 28초, 09-10 11:00).
그 뒤 추가한 큐 표시·hop 오프셋 테스트 8건까지 관련 파일 전건 통과.
